// GENERATED by proposals/017-the-job/build.py — do not hand-edit.
export const META = {
 "season": 2025,
 "modelCapture": "2026-08-07",
 "marketCapture": "2026-08-07",
 "snapshot": "2026-06-23T13:17:20.007866+00:00",
 "scoring": "PPR (verified by magnitude against known 2025 totals)",
 "starterCuts": {
  "QB": 14.55,
  "RB": 11.49,
  "WR": 11.31,
  "TE": 9.63
 },
 "starterCutRanks": {
  "QB": 24,
  "RB": 24,
  "WR": 36,
  "TE": 12
 },
 "medianRole": {
  "QB": 15.28,
  "RB": 7.16,
  "WR": 6.84,
  "TE": 5.41
 },
 "starterAnchor": {
  "QB": {
   "name": "Sam Darnold",
   "role": 14.54,
   "touches": 2.1
  },
  "RB": {
   "name": "Kimani Vidal",
   "role": 11.49,
   "touches": 14.8
  },
  "WR": {
   "name": "Alec Pierce",
   "role": 11.31,
   "touches": 5.6
  },
  "TE": {
   "name": "Zach Ertz",
   "role": 9.63,
   "touches": 5.5
  }
 },
 "tailGames": 6,
 "minGamesForTrajectory": 10,
 "populationN": 281,
 "populationRoleChange": {
  "p10": -4.14,
  "median": -0.41,
  "p75": 1.52,
  "p90": 4.21,
  "max": 9.39
 }
};
export const PLAYERS = [
 {
  "sleeperId": "11565",
  "name": "J.J. McCarthy",
  "pos": "QB",
  "team": "MIN",
  "age": 23,
  "exp": 2,
  "dvs": 60.4,
  "mktValue": 1733,
  "mktPosRank": 30,
  "mktTrend30": 40,
  "starterCut": 14.55,
  "weeks": [
   {
    "w": 1,
    "team": "MIN",
    "role": 12.61,
    "prod": 22.22,
    "tgt": 0,
    "car": 2,
    "air": 0
   },
   {
    "w": 2,
    "team": "MIN",
    "role": 12.52,
    "prod": 4.82,
    "tgt": 0,
    "car": 5,
    "air": 0
   },
   {
    "w": 9,
    "team": "MIN",
    "role": 19.36,
    "prod": 18.92,
    "tgt": 0,
    "car": 9,
    "air": 0
   },
   {
    "w": 10,
    "team": "MIN",
    "role": 27.4,
    "prod": 14.72,
    "tgt": 0,
    "car": 5,
    "air": 0
   },
   {
    "w": 11,
    "team": "MIN",
    "role": 13.57,
    "prod": 6.0,
    "tgt": 0,
    "car": 0,
    "air": 0
   },
   {
    "w": 12,
    "team": "MIN",
    "role": 5.08,
    "prod": 0.48,
    "tgt": 0,
    "car": 2,
    "air": 0
   },
   {
    "w": 14,
    "team": "MIN",
    "role": 16.57,
    "prod": 20.42,
    "tgt": 0,
    "car": 6,
    "air": 0
   },
   {
    "w": 15,
    "team": "MIN",
    "role": 25.88,
    "prod": 23.5,
    "tgt": 0,
    "car": 4,
    "air": 0
   },
   {
    "w": 16,
    "team": "MIN",
    "role": 6.73,
    "prod": 10.32,
    "tgt": 0,
    "car": 2,
    "air": 0
   },
   {
    "w": 18,
    "team": "MIN",
    "role": 12.54,
    "prod": 7.98,
    "tgt": 0,
    "car": 2,
    "air": 0
   }
  ],
  "roleFirst": 17.09,
  "roleLast6": 13.4,
  "roleChange": -3.7,
  "roleChangePctile": 0.142,
  "roleSeason": 15.23,
  "prodSeason": 12.94,
  "fpoe": -22.9,
  "teams2025": [
   "MIN"
  ]
 },
 {
  "sleeperId": "11570",
  "name": "Rasheen Ali",
  "pos": "RB",
  "team": "BAL",
  "age": 25,
  "exp": 2,
  "dvs": 20.7,
  "mktValue": 11,
  "mktPosRank": 111,
  "mktTrend30": 11,
  "starterCut": 11.49,
  "weeks": [
   {
    "w": 1,
    "team": "BAL",
    "role": 0.64,
    "prod": 0.5,
    "tgt": 0,
    "car": 1,
    "air": 0
   },
   {
    "w": 11,
    "team": "BAL",
    "role": 1.29,
    "prod": 2.5,
    "tgt": 1,
    "car": 0,
    "air": 1
   },
   {
    "w": 13,
    "team": "BAL",
    "role": 2.45,
    "prod": 1.7,
    "tgt": 0,
    "car": 4,
    "air": 0
   },
   {
    "w": 14,
    "team": "BAL",
    "role": 5.11,
    "prod": 3.3,
    "tgt": 3,
    "car": 1,
    "air": 11
   },
   {
    "w": 15,
    "team": "BAL",
    "role": 2.96,
    "prod": 11.2,
    "tgt": 2,
    "car": 0,
    "air": -6
   },
   {
    "w": 16,
    "team": "BAL",
    "role": 2.85,
    "prod": 2.2,
    "tgt": 2,
    "car": 0,
    "air": -13
   },
   {
    "w": 17,
    "team": "BAL",
    "role": 3.89,
    "prod": 2.8,
    "tgt": 3,
    "car": 0,
    "air": 6
   },
   {
    "w": 18,
    "team": "BAL",
    "role": 0.52,
    "prod": 0.0,
    "tgt": 0,
    "car": 1,
    "air": 0
   }
  ]
 },
 {
  "sleeperId": "11576",
  "name": "Braelon Allen",
  "pos": "RB",
  "team": "NYJ",
  "age": 22,
  "exp": 2,
  "dvs": null,
  "mktValue": 1135,
  "mktPosRank": 55,
  "mktTrend30": -76,
  "starterCut": 11.49,
  "weeks": [
   {
    "w": 1,
    "team": "NYJ",
    "role": 4.47,
    "prod": 6.9,
    "tgt": 0,
    "car": 6,
    "air": 0
   },
   {
    "w": 2,
    "team": "NYJ",
    "role": 5.25,
    "prod": 1.1,
    "tgt": 1,
    "car": 2,
    "air": 0
   },
   {
    "w": 3,
    "team": "NYJ",
    "role": 6.13,
    "prod": 6.7,
    "tgt": 2,
    "car": 6,
    "air": 8
   },
   {
    "w": 4,
    "team": "NYJ",
    "role": 2.2,
    "prod": 0.6,
    "tgt": 0,
    "car": 4,
    "air": 0
   }
  ]
 },
 {
  "sleeperId": "11597",
  "name": "Theo Johnson",
  "pos": "TE",
  "team": "NYG",
  "age": 25,
  "exp": 2,
  "dvs": 81.1,
  "mktValue": 756,
  "mktPosRank": 34,
  "mktTrend30": 49,
  "starterCut": 9.63,
  "weeks": [
   {
    "w": 1,
    "team": "NYG",
    "role": 3.97,
    "prod": 1.5,
    "tgt": 3,
    "car": 0,
    "air": -2
   },
   {
    "w": 2,
    "team": "NYG",
    "role": 8.51,
    "prod": 7.4,
    "tgt": 5,
    "car": 0,
    "air": 42
   },
   {
    "w": 3,
    "team": "NYG",
    "role": 3.45,
    "prod": 2.0,
    "tgt": 2,
    "car": 0,
    "air": 7
   },
   {
    "w": 4,
    "team": "NYG",
    "role": 10.07,
    "prod": 10.7,
    "tgt": 5,
    "car": 0,
    "air": 38
   },
   {
    "w": 5,
    "team": "NYG",
    "role": 15.88,
    "prod": 21.3,
    "tgt": 7,
    "car": 0,
    "air": 40
   },
   {
    "w": 6,
    "team": "NYG",
    "role": 5.73,
    "prod": 4.7,
    "tgt": 4,
    "car": 0,
    "air": 39
   },
   {
    "w": 7,
    "team": "NYG",
    "role": 9.77,
    "prod": 15.6,
    "tgt": 7,
    "car": 0,
    "air": 32
   },
   {
    "w": 8,
    "team": "NYG",
    "role": 6.19,
    "prod": 5.0,
    "tgt": 4,
    "car": 0,
    "air": 36
   },
   {
    "w": 9,
    "team": "NYG",
    "role": 9.85,
    "prod": 11.7,
    "tgt": 6,
    "car": 0,
    "air": 46
   },
   {
    "w": 10,
    "team": "NYG",
    "role": 13.31,
    "prod": 14.5,
    "tgt": 8,
    "car": 0,
    "air": 72
   },
   {
    "w": 11,
    "team": "NYG",
    "role": 5.14,
    "prod": 6.6,
    "tgt": 4,
    "car": 0,
    "air": 34
   },
   {
    "w": 12,
    "team": "NYG",
    "role": 13.91,
    "prod": 10.7,
    "tgt": 5,
    "car": 0,
    "air": 79
   },
   {
    "w": 13,
    "team": "NYG",
    "role": 11.93,
    "prod": 5.9,
    "tgt": 8,
    "car": 0,
    "air": 103
   },
   {
    "w": 15,
    "team": "NYG",
    "role": 5.97,
    "prod": 10.2,
    "tgt": 4,
    "car": 0,
    "air": 43
   },
   {
    "w": 16,
    "team": "NYG",
    "role": 3.17,
    "prod": 0.0,
    "tgt": 2,
    "car": 0,
    "air": 7
   }
  ],
  "roleFirst": 8.2,
  "roleLast6": 8.9,
  "roleChange": 0.71,
  "roleChangePctile": 0.63,
  "roleSeason": 8.46,
  "prodSeason": 8.52,
  "fpoe": 1.0,
  "teams2025": [
   "NYG"
  ]
 },
 {
  "sleeperId": "11603",
  "name": "AJ Barner",
  "pos": "TE",
  "team": "SEA",
  "age": 24,
  "exp": 2,
  "dvs": 86.9,
  "mktValue": 1498,
  "mktPosRank": 21,
  "mktTrend30": 2,
  "starterCut": 9.63,
  "weeks": [
   {
    "w": 1,
    "team": "SEA",
    "role": 2.82,
    "prod": 1.2,
    "tgt": 2,
    "car": 1,
    "air": 3
   },
   {
    "w": 2,
    "team": "SEA",
    "role": 7.07,
    "prod": 10.8,
    "tgt": 3,
    "car": 1,
    "air": -1
   },
   {
    "w": 3,
    "team": "SEA",
    "role": 2.28,
    "prod": 3.3,
    "tgt": 1,
    "car": 0,
    "air": 20
   },
   {
    "w": 4,
    "team": "SEA",
    "role": 7.38,
    "prod": 12.2,
    "tgt": 3,
    "car": 0,
    "air": 22
   },
   {
    "w": 5,
    "team": "SEA",
    "role": 13.57,
    "prod": 24.3,
    "tgt": 7,
    "car": 0,
    "air": 29
   },
   {
    "w": 6,
    "team": "SEA",
    "role": 5.37,
    "prod": 10.1,
    "tgt": 3,
    "car": 0,
    "air": 40
   },
   {
    "w": 7,
    "team": "SEA",
    "role": 4.95,
    "prod": 1.9,
    "tgt": 3,
    "car": 1,
    "air": 13
   },
   {
    "w": 9,
    "team": "SEA",
    "role": 12.04,
    "prod": 11.5,
    "tgt": 4,
    "car": 1,
    "air": 16
   },
   {
    "w": 10,
    "team": "SEA",
    "role": 0.59,
    "prod": 0.3,
    "tgt": 0,
    "car": 2,
    "air": 0
   },
   {
    "w": 11,
    "team": "SEA",
    "role": 17.78,
    "prod": 17.1,
    "tgt": 11,
    "car": 2,
    "air": 30
   },
   {
    "w": 12,
    "team": "SEA",
    "role": 8.57,
    "prod": 3.8,
    "tgt": 4,
    "car": 0,
    "air": 29
   },
   {
    "w": 13,
    "team": "SEA",
    "role": 7.9,
    "prod": 7.7,
    "tgt": 5,
    "car": 1,
    "air": 9
   },
   {
    "w": 14,
    "team": "SEA",
    "role": 9.73,
    "prod": 5.7,
    "tgt": 4,
    "car": 0,
    "air": 14
   },
   {
    "w": 15,
    "team": "SEA",
    "role": 6.87,
    "prod": 5.7,
    "tgt": 6,
    "car": 0,
    "air": 23
   },
   {
    "w": 16,
    "team": "SEA",
    "role": 10.1,
    "prod": 15.0,
    "tgt": 6,
    "car": 1,
    "air": 31
   },
   {
    "w": 17,
    "team": "SEA",
    "role": 4.01,
    "prod": 13.3,
    "tgt": 3,
    "car": 0,
    "air": 10
   },
   {
    "w": 18,
    "team": "SEA",
    "role": 4.19,
    "prod": 3.4,
    "tgt": 3,
    "car": 0,
    "air": 9
   }
  ],
  "roleFirst": 6.94,
  "roleLast6": 7.13,
  "roleChange": 0.2,
  "roleChangePctile": 0.559,
  "roleSeason": 7.37,
  "prodSeason": 8.66,
  "fpoe": 22.1,
  "teams2025": [
   "SEA"
  ]
 },
 {
  "sleeperId": "11620",
  "name": "Rome Odunze",
  "pos": "WR",
  "team": "CHI",
  "age": 24,
  "exp": 2,
  "dvs": 69.0,
  "mktValue": 3321,
  "mktPosRank": 24,
  "mktTrend30": 59,
  "starterCut": 11.31,
  "weeks": [
   {
    "w": 1,
    "team": "CHI",
    "role": 15.98,
    "prod": 13.7,
    "tgt": 9,
    "car": 0,
    "air": 55
   },
   {
    "w": 2,
    "team": "CHI",
    "role": 22.72,
    "prod": 31.8,
    "tgt": 11,
    "car": 0,
    "air": 200
   },
   {
    "w": 3,
    "team": "CHI",
    "role": 13.06,
    "prod": 15.2,
    "tgt": 7,
    "car": 0,
    "air": 79
   },
   {
    "w": 4,
    "team": "CHI",
    "role": 17.0,
    "prod": 16.9,
    "tgt": 8,
    "car": 0,
    "air": 96
   },
   {
    "w": 6,
    "team": "CHI",
    "role": 9.06,
    "prod": 5.2,
    "tgt": 5,
    "car": 0,
    "air": 98
   },
   {
    "w": 7,
    "team": "CHI",
    "role": 8.78,
    "prod": 5.1,
    "tgt": 6,
    "car": 0,
    "air": 81
   },
   {
    "w": 8,
    "team": "CHI",
    "role": 17.88,
    "prod": 18.4,
    "tgt": 10,
    "car": 0,
    "air": 147
   },
   {
    "w": 9,
    "team": "CHI",
    "role": 8.11,
    "prod": 0.0,
    "tgt": 3,
    "car": 0,
    "air": 35
   },
   {
    "w": 10,
    "team": "CHI",
    "role": 20.13,
    "prod": 20.6,
    "tgt": 10,
    "car": 0,
    "air": 143
   },
   {
    "w": 11,
    "team": "CHI",
    "role": 14.23,
    "prod": 6.1,
    "tgt": 6,
    "car": 0,
    "air": 144
   },
   {
    "w": 12,
    "team": "CHI",
    "role": 15.68,
    "prod": 8.3,
    "tgt": 9,
    "car": 0,
    "air": 117
   },
   {
    "w": 13,
    "team": "CHI",
    "role": 9.83,
    "prod": 2.8,
    "tgt": 6,
    "car": 0,
    "air": 57
   }
  ],
  "roleFirst": 14.43,
  "roleLast6": 14.31,
  "roleChange": -0.12,
  "roleChangePctile": 0.52,
  "roleSeason": 14.37,
  "prodSeason": 12.01,
  "fpoe": -28.4,
  "teams2025": [
   "CHI"
  ]
 },
 {
  "sleeperId": "11625",
  "name": "Adonai Mitchell",
  "pos": "WR",
  "team": "NYJ",
  "age": 23,
  "exp": 2,
  "dvs": 40.1,
  "mktValue": 1204,
  "mktPosRank": 74,
  "mktTrend30": -3,
  "starterCut": 11.31,
  "weeks": [
   {
    "w": 1,
    "team": "IND",
    "role": 3.49,
    "prod": 4.1,
    "tgt": 2,
    "car": 0,
    "air": 21
   },
   {
    "w": 2,
    "team": "IND",
    "role": 9.07,
    "prod": 4.0,
    "tgt": 4,
    "car": 0,
    "air": 107
   },
   {
    "w": 3,
    "team": "IND",
    "role": 2.73,
    "prod": 0.0,
    "tgt": 2,
    "car": 0,
    "air": -1
   },
   {
    "w": 4,
    "team": "IND",
    "role": 7.42,
    "prod": 10.6,
    "tgt": 4,
    "car": 0,
    "air": 87
   },
   {
    "w": 5,
    "team": "IND",
    "role": 2.22,
    "prod": 0.0,
    "tgt": 1,
    "car": 0,
    "air": 29
   },
   {
    "w": 7,
    "team": "IND",
    "role": 1.49,
    "prod": 1.8,
    "tgt": 1,
    "car": 0,
    "air": 4
   },
   {
    "w": 8,
    "team": "IND",
    "role": 1.57,
    "prod": 0.0,
    "tgt": 1,
    "car": 0,
    "air": 4
   },
   {
    "w": 9,
    "team": "IND",
    "role": 1.5,
    "prod": 1.7,
    "tgt": 1,
    "car": 0,
    "air": 7
   },
   {
    "w": 11,
    "team": "NYJ",
    "role": 8.97,
    "prod": 2.0,
    "tgt": 6,
    "car": 0,
    "air": 104
   },
   {
    "w": 12,
    "team": "NYJ",
    "role": 12.03,
    "prod": 6.2,
    "tgt": 7,
    "car": 0,
    "air": 182
   },
   {
    "w": 13,
    "team": "NYJ",
    "role": 19.11,
    "prod": 24.2,
    "tgt": 12,
    "car": 0,
    "air": 173
   },
   {
    "w": 14,
    "team": "NYJ",
    "role": 9.59,
    "prod": 3.4,
    "tgt": 6,
    "car": 0,
    "air": 78
   },
   {
    "w": 15,
    "team": "NYJ",
    "role": 13.46,
    "prod": 17.4,
    "tgt": 9,
    "car": 1,
    "air": 88
   },
   {
    "w": 16,
    "team": "NYJ",
    "role": 7.87,
    "prod": 7.3,
    "tgt": 6,
    "car": 0,
    "air": 72
   },
   {
    "w": 17,
    "team": "NYJ",
    "role": 11.89,
    "prod": 5.2,
    "tgt": 9,
    "car": 0,
    "air": 116
   },
   {
    "w": 18,
    "team": "NYJ",
    "role": 3.73,
    "prod": 0.0,
    "tgt": 3,
    "car": 0,
    "air": 31
   }
  ],
  "roleFirst": 3.69,
  "roleLast6": 10.94,
  "roleChange": 7.26,
  "roleChangePctile": 0.979,
  "roleSeason": 7.26,
  "prodSeason": 5.49,
  "fpoe": -28.2,
  "teams2025": [
   "IND",
   "NYJ"
  ],
  "byTeam": {
   "IND": {
    "g": 8,
    "role": 3.69,
    "weeks": [
     1,
     2,
     3,
     4,
     5,
     7,
     8,
     9
    ]
   },
   "NYJ": {
    "g": 8,
    "role": 10.83,
    "weeks": [
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18
    ]
   }
  }
 },
 {
  "sleeperId": "11626",
  "name": "Xavier Legette",
  "pos": "WR",
  "team": "CAR",
  "age": 25,
  "exp": 2,
  "dvs": 44.2,
  "mktValue": 551,
  "mktPosRank": 101,
  "mktTrend30": 39,
  "starterCut": 11.31,
  "weeks": [
   {
    "w": 1,
    "team": "CAR",
    "role": 12.66,
    "prod": 4.0,
    "tgt": 7,
    "car": 0,
    "air": 61
   },
   {
    "w": 2,
    "team": "CAR",
    "role": 14.67,
    "prod": 0.8,
    "tgt": 8,
    "car": 1,
    "air": 33
   },
   {
    "w": 5,
    "team": "CAR",
    "role": 7.01,
    "prod": 11.1,
    "tgt": 3,
    "car": 0,
    "air": 51
   },
   {
    "w": 6,
    "team": "CAR",
    "role": 2.76,
    "prod": 3.1,
    "tgt": 2,
    "car": 0,
    "air": -1
   },
   {
    "w": 7,
    "team": "CAR",
    "role": 19.53,
    "prod": 24.2,
    "tgt": 11,
    "car": 0,
    "air": 102
   },
   {
    "w": 8,
    "team": "CAR",
    "role": 4.67,
    "prod": 3.7,
    "tgt": 3,
    "car": 0,
    "air": 22
   },
   {
    "w": 9,
    "team": "CAR",
    "role": 5.16,
    "prod": 3.2,
    "tgt": 3,
    "car": 0,
    "air": 37
   },
   {
    "w": 10,
    "team": "CAR",
    "role": 1.61,
    "prod": 0.0,
    "tgt": 1,
    "car": 0,
    "air": 30
   },
   {
    "w": 11,
    "team": "CAR",
    "role": 13.8,
    "prod": 18.3,
    "tgt": 8,
    "car": 0,
    "air": 102
   },
   {
    "w": 12,
    "team": "CAR",
    "role": 7.71,
    "prod": 5.2,
    "tgt": 5,
    "car": 0,
    "air": 54
   },
   {
    "w": 13,
    "team": "CAR",
    "role": 3.0,
    "prod": 1.1,
    "tgt": 2,
    "car": 0,
    "air": 26
   },
   {
    "w": 15,
    "team": "CAR",
    "role": 4.2,
    "prod": 5.9,
    "tgt": 3,
    "car": 0,
    "air": 42
   },
   {
    "w": 16,
    "team": "CAR",
    "role": 3.54,
    "prod": 2.2,
    "tgt": 3,
    "car": 0,
    "air": 30
   },
   {
    "w": 17,
    "team": "CAR",
    "role": 1.26,
    "prod": 1.3,
    "tgt": 1,
    "car": 0,
    "air": 3
   },
   {
    "w": 18,
    "team": "CAR",
    "role": 6.41,
    "prod": 5.2,
    "tgt": 4,
    "car": 0,
    "air": 41
   }
  ],
  "roleFirst": 9.49,
  "roleLast6": 4.35,
  "roleChange": -5.14,
  "roleChangePctile": 0.06,
  "roleSeason": 7.2,
  "prodSeason": 5.95,
  "fpoe": -18.7,
  "teams2025": [
   "CAR"
  ]
 },
 {
  "sleeperId": "12486",
  "name": "Dillon Gabriel",
  "pos": "QB",
  "team": "CLE",
  "age": 25,
  "exp": 1,
  "dvs": 49.7,
  "mktValue": 131,
  "mktPosRank": 61,
  "mktTrend30": -36,
  "starterCut": 14.55,
  "weeks": [
   {
    "w": 2,
    "team": "CLE",
    "role": 1.7,
    "prod": 4.76,
    "tgt": 0,
    "car": 0,
    "air": 0
   },
   {
    "w": 4,
    "team": "CLE",
    "role": 0.33,
    "prod": 0.0,
    "tgt": 0,
    "car": 0,
    "air": 0
   },
   {
    "w": 5,
    "team": "CLE",
    "role": 16.73,
    "prod": 16.1,
    "tgt": 0,
    "car": 2,
    "air": 0
   },
   {
    "w": 6,
    "team": "CLE",
    "role": 13.99,
    "prod": 8.84,
    "tgt": 0,
    "car": 0,
    "air": 0
   },
   {
    "w": 7,
    "team": "CLE",
    "role": 7.41,
    "prod": 5.84,
    "tgt": 0,
    "car": 4,
    "air": 0
   },
   {
    "w": 8,
    "team": "CLE",
    "role": 15.23,
    "prod": 11.54,
    "tgt": 0,
    "car": 1,
    "air": 0
   },
   {
    "w": 10,
    "team": "CLE",
    "role": 14.52,
    "prod": 20.08,
    "tgt": 0,
    "car": 5,
    "air": 0
   },
   {
    "w": 11,
    "team": "CLE",
    "role": 4.64,
    "prod": 2.92,
    "tgt": 0,
    "car": 2,
    "air": 0
   },
   {
    "w": 13,
    "team": "CLE",
    "role": 0.19,
    "prod": 0.0,
    "tgt": 0,
    "car": 0,
    "air": 0
   }
  ]
 },
 {
  "sleeperId": "12492",
  "name": "Pat Bryant",
  "pos": "WR",
  "team": "DEN",
  "age": 23,
  "exp": 1,
  "dvs": 46.4,
  "mktValue": 1061,
  "mktPosRank": 81,
  "mktTrend30": 90,
  "starterCut": 11.31,
  "weeks": [
   {
    "w": 2,
    "team": "DEN",
    "role": 4.21,
    "prod": 3.8,
    "tgt": 3,
    "car": 0,
    "air": 8
   },
   {
    "w": 4,
    "team": "DEN",
    "role": 3.59,
    "prod": 0.0,
    "tgt": 1,
    "car": 0,
    "air": 6
   },
   {
    "w": 6,
    "team": "DEN",
    "role": 2.87,
    "prod": 4.2,
    "tgt": 2,
    "car": 0,
    "air": 10
   },
   {
    "w": 7,
    "team": "DEN",
    "role": 6.09,
    "prod": 1.6,
    "tgt": 4,
    "car": 0,
    "air": 18
   },
   {
    "w": 8,
    "team": "DEN",
    "role": 9.08,
    "prod": 12.0,
    "tgt": 4,
    "car": 0,
    "air": 60
   },
   {
    "w": 9,
    "team": "DEN",
    "role": 5.4,
    "prod": 4.0,
    "tgt": 3,
    "car": 0,
    "air": 57
   },
   {
    "w": 10,
    "team": "DEN",
    "role": 3.06,
    "prod": 5.3,
    "tgt": 2,
    "car": 0,
    "air": 22
   },
   {
    "w": 11,
    "team": "DEN",
    "role": 9.46,
    "prod": 13.2,
    "tgt": 6,
    "car": 0,
    "air": 57
   },
   {
    "w": 13,
    "team": "DEN",
    "role": 10.57,
    "prod": 7.2,
    "tgt": 7,
    "car": 0,
    "air": 66
   },
   {
    "w": 14,
    "team": "DEN",
    "role": 6.39,
    "prod": 7.2,
    "tgt": 4,
    "car": 0,
    "air": 20
   },
   {
    "w": 16,
    "team": "DEN",
    "role": 12.33,
    "prod": 9.2,
    "tgt": 8,
    "car": 0,
    "air": 67
   },
   {
    "w": 18,
    "team": "DEN",
    "role": 8.71,
    "prod": 7.1,
    "tgt": 5,
    "car": 0,
    "air": 19
   }
  ],
  "roleFirst": 5.21,
  "roleLast6": 8.42,
  "roleChange": 3.21,
  "roleChangePctile": 0.872,
  "roleSeason": 6.81,
  "prodSeason": 6.23,
  "fpoe": -7.0,
  "teams2025": [
   "DEN"
  ]
 },
 {
  "sleeperId": "12499",
  "name": "Elic Ayomanor",
  "pos": "WR",
  "team": "TEN",
  "age": 23,
  "exp": 1,
  "dvs": 56.4,
  "mktValue": 1067,
  "mktPosRank": 80,
  "mktTrend30": 226,
  "starterCut": 11.31,
  "weeks": [
   {
    "w": 1,
    "team": "TEN",
    "role": 10.26,
    "prod": 3.3,
    "tgt": 7,
    "car": 0,
    "air": 133
   },
   {
    "w": 2,
    "team": "TEN",
    "role": 8.72,
    "prod": 15.6,
    "tgt": 6,
    "car": 0,
    "air": 69
   },
   {
    "w": 3,
    "team": "TEN",
    "role": 10.23,
    "prod": 13.8,
    "tgt": 5,
    "car": 0,
    "air": 39
   },
   {
    "w": 4,
    "team": "TEN",
    "role": 10.16,
    "prod": 6.4,
    "tgt": 7,
    "car": 0,
    "air": 102
   },
   {
    "w": 5,
    "team": "TEN",
    "role": 5.52,
    "prod": 3.8,
    "tgt": 4,
    "car": 0,
    "air": 38
   },
   {
    "w": 6,
    "team": "TEN",
    "role": 6.71,
    "prod": 5.7,
    "tgt": 5,
    "car": 0,
    "air": 84
   },
   {
    "w": 7,
    "team": "TEN",
    "role": 6.99,
    "prod": 4.9,
    "tgt": 5,
    "car": 0,
    "air": 37
   },
   {
    "w": 8,
    "team": "TEN",
    "role": 14.77,
    "prod": 9.2,
    "tgt": 8,
    "car": 0,
    "air": 111
   },
   {
    "w": 9,
    "team": "TEN",
    "role": 9.37,
    "prod": 7.6,
    "tgt": 6,
    "car": 0,
    "air": 72
   },
   {
    "w": 11,
    "team": "TEN",
    "role": 8.41,
    "prod": 3.1,
    "tgt": 6,
    "car": 0,
    "air": 75
   },
   {
    "w": 13,
    "team": "TEN",
    "role": 7.46,
    "prod": 1.5,
    "tgt": 5,
    "car": 0,
    "air": 57
   },
   {
    "w": 14,
    "team": "TEN",
    "role": 4.2,
    "prod": 8.4,
    "tgt": 3,
    "car": 0,
    "air": 22
   },
   {
    "w": 15,
    "team": "TEN",
    "role": 1.77,
    "prod": 2.7,
    "tgt": 1,
    "car": 0,
    "air": 15
   },
   {
    "w": 16,
    "team": "TEN",
    "role": 6.58,
    "prod": 8.8,
    "tgt": 4,
    "car": 0,
    "air": 80
   },
   {
    "w": 17,
    "team": "TEN",
    "role": 13.73,
    "prod": 13.7,
    "tgt": 7,
    "car": 0,
    "air": 70
   },
   {
    "w": 18,
    "team": "TEN",
    "role": 13.93,
    "prod": 8.0,
    "tgt": 10,
    "car": 0,
    "air": 122
   }
  ],
  "roleFirst": 9.17,
  "roleLast6": 7.95,
  "roleChange": -1.22,
  "roleChangePctile": 0.377,
  "roleSeason": 8.68,
  "prodSeason": 7.28,
  "fpoe": -22.3,
  "teams2025": [
   "TEN"
  ]
 },
 {
  "sleeperId": "12508",
  "name": "Jaxson Dart",
  "pos": "QB",
  "team": "NYG",
  "age": 23,
  "exp": 1,
  "dvs": 77.5,
  "mktValue": 5237,
  "mktPosRank": 10,
  "mktTrend30": -130,
  "starterCut": 14.55,
  "weeks": [
   {
    "w": 2,
    "team": "NYG",
    "role": 0.69,
    "prod": -0.3,
    "tgt": 0,
    "car": 1,
    "air": 0
   },
   {
    "w": 3,
    "team": "NYG",
    "role": 0.72,
    "prod": 0.3,
    "tgt": 0,
    "car": 1,
    "air": 0
   },
   {
    "w": 4,
    "team": "NYG",
    "role": 19.66,
    "prod": 19.84,
    "tgt": 0,
    "car": 10,
    "air": 0
   },
   {
    "w": 5,
    "team": "NYG",
    "role": 22.22,
    "prod": 17.58,
    "tgt": 0,
    "car": 7,
    "air": 0
   },
   {
    "w": 6,
    "team": "NYG",
    "role": 18.56,
    "prod": 23.6,
    "tgt": 0,
    "car": 13,
    "air": 0
   },
   {
    "w": 7,
    "team": "NYG",
    "role": 18.22,
    "prod": 28.42,
    "tgt": 0,
    "car": 5,
    "air": 0
   },
   {
    "w": 8,
    "team": "NYG",
    "role": 17.45,
    "prod": 19.42,
    "tgt": 0,
    "car": 6,
    "air": 0
   },
   {
    "w": 9,
    "team": "NYG",
    "role": 21.65,
    "prod": 27.24,
    "tgt": 0,
    "car": 8,
    "air": 0
   },
   {
    "w": 10,
    "team": "NYG",
    "role": 20.45,
    "prod": 26.28,
    "tgt": 0,
    "car": 6,
    "air": 0
   },
   {
    "w": 13,
    "team": "NYG",
    "role": 10.0,
    "prod": 13.56,
    "tgt": 0,
    "car": 4,
    "air": 0
   },
   {
    "w": 15,
    "team": "NYG",
    "role": 25.18,
    "prod": 22.14,
    "tgt": 0,
    "car": 9,
    "air": 0
   },
   {
    "w": 16,
    "team": "NYG",
    "role": 4.57,
    "prod": 0.02,
    "tgt": 0,
    "car": 2,
    "air": 0
   },
   {
    "w": 17,
    "team": "NYG",
    "role": 19.25,
    "prod": 25.08,
    "tgt": 0,
    "car": 9,
    "air": 0
   },
   {
    "w": 18,
    "team": "NYG",
    "role": 21.35,
    "prod": 20.4,
    "tgt": 0,
    "car": 5,
    "air": 0
   }
  ],
  "roleFirst": 13.93,
  "roleLast6": 16.8,
  "roleChange": 2.87,
  "roleChangePctile": 0.847,
  "roleSeason": 15.71,
  "prodSeason": 17.4,
  "fpoe": 23.6,
  "teams2025": [
   "NYG"
  ]
 },
 {
  "sleeperId": "12509",
  "name": "Tre' Harris",
  "pos": "WR",
  "team": "LAC",
  "age": 24,
  "exp": 1,
  "dvs": 43.1,
  "mktValue": 1279,
  "mktPosRank": 68,
  "mktTrend30": -11,
  "starterCut": 11.31,
  "weeks": [
   {
    "w": 1,
    "team": "LAC",
    "role": 1.49,
    "prod": 2.1,
    "tgt": 1,
    "car": 0,
    "air": 5
   },
   {
    "w": 2,
    "team": "LAC",
    "role": 4.94,
    "prod": 5.4,
    "tgt": 3,
    "car": 0,
    "air": 32
   },
   {
    "w": 3,
    "team": "LAC",
    "role": 1.44,
    "prod": 0.0,
    "tgt": 1,
    "car": 0,
    "air": 34
   },
   {
    "w": 4,
    "team": "LAC",
    "role": 1.25,
    "prod": 0.0,
    "tgt": 1,
    "car": 0,
    "air": -5
   },
   {
    "w": 6,
    "team": "LAC",
    "role": 8.25,
    "prod": 6.7,
    "tgt": 5,
    "car": 0,
    "air": 33
   },
   {
    "w": 7,
    "team": "LAC",
    "role": 3.5,
    "prod": 4.3,
    "tgt": 2,
    "car": 0,
    "air": 18
   },
   {
    "w": 8,
    "team": "LAC",
    "role": 5.59,
    "prod": 8.8,
    "tgt": 2,
    "car": 0,
    "air": 8
   },
   {
    "w": 9,
    "team": "LAC",
    "role": 3.05,
    "prod": 3.8,
    "tgt": 2,
    "car": 0,
    "air": 12
   },
   {
    "w": 10,
    "team": "LAC",
    "role": 2.87,
    "prod": 2.4,
    "tgt": 2,
    "car": 0,
    "air": -6
   },
   {
    "w": 11,
    "team": "LAC",
    "role": 1.4,
    "prod": 2.2,
    "tgt": 1,
    "car": 0,
    "air": -3
   },
   {
    "w": 13,
    "team": "LAC",
    "role": 6.33,
    "prod": 6.0,
    "tgt": 4,
    "car": 0,
    "air": 44
   },
   {
    "w": 14,
    "team": "LAC",
    "role": 3.93,
    "prod": 3.1,
    "tgt": 2,
    "car": 1,
    "air": 26
   },
   {
    "w": 15,
    "team": "LAC",
    "role": 6.91,
    "prod": 7.9,
    "tgt": 5,
    "car": 0,
    "air": 57
   },
   {
    "w": 16,
    "team": "LAC",
    "role": 8.0,
    "prod": 9.4,
    "tgt": 5,
    "car": 0,
    "air": 36
   },
   {
    "w": 17,
    "team": "LAC",
    "role": 2.36,
    "prod": 2.5,
    "tgt": 1,
    "car": 1,
    "air": -1
   },
   {
    "w": 18,
    "team": "LAC",
    "role": 8.15,
    "prod": 4.8,
    "tgt": 6,
    "car": 0,
    "air": 108
   }
  ],
  "roleFirst": 3.69,
  "roleLast6": 5.95,
  "roleChange": 2.26,
  "roleChangePctile": 0.826,
  "roleSeason": 4.34,
  "prodSeason": 4.34,
  "fpoe": -0.1,
  "teams2025": [
   "LAC"
  ]
 },
 {
  "sleeperId": "12519",
  "name": "Luther Burden",
  "pos": "WR",
  "team": "CHI",
  "age": 22,
  "exp": 1,
  "dvs": 63.3,
  "mktValue": 3792,
  "mktPosRank": 18,
  "mktTrend30": 313,
  "starterCut": 11.31,
  "weeks": [
   {
    "w": 1,
    "team": "CHI",
    "role": 1.4,
    "prod": 0.7,
    "tgt": 1,
    "car": 0,
    "air": -5
   },
   {
    "w": 2,
    "team": "CHI",
    "role": 3.42,
    "prod": 1.5,
    "tgt": 2,
    "car": 0,
    "air": 6
   },
   {
    "w": 3,
    "team": "CHI",
    "role": 7.82,
    "prod": 19.8,
    "tgt": 3,
    "car": 1,
    "air": 64
   },
   {
    "w": 4,
    "team": "CHI",
    "role": 2.92,
    "prod": 1.6,
    "tgt": 2,
    "car": 0,
    "air": -7
   },
   {
    "w": 6,
    "team": "CHI",
    "role": 5.85,
    "prod": 9.1,
    "tgt": 4,
    "car": 0,
    "air": 15
   },
   {
    "w": 7,
    "team": "CHI",
    "role": 4.96,
    "prod": 3.1,
    "tgt": 2,
    "car": 1,
    "air": 39
   },
   {
    "w": 8,
    "team": "CHI",
    "role": 1.34,
    "prod": 0.9,
    "tgt": 1,
    "car": 0,
    "air": -3
   },
   {
    "w": 10,
    "team": "CHI",
    "role": 5.3,
    "prod": 8.1,
    "tgt": 3,
    "car": 0,
    "air": 34
   },
   {
    "w": 11,
    "team": "CHI",
    "role": 7.84,
    "prod": 5.7,
    "tgt": 5,
    "car": 0,
    "air": 37
   },
   {
    "w": 12,
    "team": "CHI",
    "role": 8.65,
    "prod": 9.1,
    "tgt": 5,
    "car": 1,
    "air": 38
   },
   {
    "w": 13,
    "team": "CHI",
    "role": 9.95,
    "prod": 7.6,
    "tgt": 6,
    "car": 1,
    "air": 32
   },
   {
    "w": 14,
    "team": "CHI",
    "role": 9.59,
    "prod": 11.0,
    "tgt": 6,
    "car": 1,
    "air": 60
   },
   {
    "w": 15,
    "team": "CHI",
    "role": 10.23,
    "prod": 14.4,
    "tgt": 7,
    "car": 0,
    "air": 50
   },
   {
    "w": 17,
    "team": "CHI",
    "role": 14.5,
    "prod": 27.8,
    "tgt": 9,
    "car": 0,
    "air": 88
   },
   {
    "w": 18,
    "team": "CHI",
    "role": 6.53,
    "prod": 7.5,
    "tgt": 4,
    "car": 1,
    "air": 12
   }
  ],
  "roleFirst": 3.96,
  "roleLast6": 9.91,
  "roleChange": 5.95,
  "roleChangePctile": 0.95,
  "roleSeason": 6.69,
  "prodSeason": 8.53,
  "fpoe": 27.6,
  "teams2025": [
   "CHI"
  ]
 },
 {
  "sleeperId": "12527",
  "name": "Ashton Jeanty",
  "pos": "RB",
  "team": "LV",
  "age": 22,
  "exp": 1,
  "dvs": 75.3,
  "mktValue": 6983,
  "mktPosRank": 3,
  "mktTrend30": -365,
  "starterCut": 11.49,
  "weeks": [
   {
    "w": 1,
    "team": "LV",
    "role": 12.9,
    "prod": 12.0,
    "tgt": 2,
    "car": 19,
    "air": -4
   },
   {
    "w": 2,
    "team": "LV",
    "role": 10.93,
    "prod": 7.4,
    "tgt": 4,
    "car": 11,
    "air": -27
   },
   {
    "w": 3,
    "team": "LV",
    "role": 8.54,
    "prod": 6.3,
    "tgt": 0,
    "car": 17,
    "air": 0
   },
   {
    "w": 4,
    "team": "LV",
    "role": 17.44,
    "prod": 33.5,
    "tgt": 2,
    "car": 21,
    "air": 7
   },
   {
    "w": 5,
    "team": "LV",
    "role": 16.84,
    "prod": 15.9,
    "tgt": 7,
    "car": 14,
    "air": -5
   },
   {
    "w": 6,
    "team": "LV",
    "role": 23.04,
    "prod": 16.6,
    "tgt": 4,
    "car": 23,
    "air": -13
   },
   {
    "w": 7,
    "team": "LV",
    "role": 4.15,
    "prod": 4.4,
    "tgt": 1,
    "car": 6,
    "air": -5
   },
   {
    "w": 9,
    "team": "LV",
    "role": 18.5,
    "prod": 19.9,
    "tgt": 5,
    "car": 13,
    "air": -19
   },
   {
    "w": 10,
    "team": "LV",
    "role": 15.86,
    "prod": 15.3,
    "tgt": 5,
    "car": 19,
    "air": -14
   },
   {
    "w": 11,
    "team": "LV",
    "role": 13.47,
    "prod": 9.4,
    "tgt": 8,
    "car": 6,
    "air": -21
   },
   {
    "w": 12,
    "team": "LV",
    "role": 20.34,
    "prod": 24.8,
    "tgt": 8,
    "car": 17,
    "air": -20
   },
   {
    "w": 13,
    "team": "LV",
    "role": 20.14,
    "prod": 12.1,
    "tgt": 8,
    "car": 15,
    "air": -27
   },
   {
    "w": 14,
    "team": "LV",
    "role": 9.95,
    "prod": 5.8,
    "tgt": 4,
    "car": 10,
    "air": 19
   },
   {
    "w": 15,
    "team": "LV",
    "role": 11.32,
    "prod": 8.2,
    "tgt": 6,
    "car": 9,
    "air": 4
   },
   {
    "w": 16,
    "team": "LV",
    "role": 13.63,
    "prod": 31.8,
    "tgt": 2,
    "car": 24,
    "air": 27
   },
   {
    "w": 17,
    "team": "LV",
    "role": 11.7,
    "prod": 9.3,
    "tgt": 2,
    "car": 16,
    "air": 9
   },
   {
    "w": 18,
    "team": "LV",
    "role": 20.21,
    "prod": 12.4,
    "tgt": 5,
    "car": 26,
    "air": -15
   }
  ],
  "roleFirst": 14.04,
  "roleLast6": 14.49,
  "roleChange": 0.45,
  "roleChangePctile": 0.577,
  "roleSeason": 14.64,
  "prodSeason": 14.42,
  "fpoe": -3.9,
  "teams2025": [
   "LV"
  ]
 },
 {
  "sleeperId": "12529",
  "name": "TreVeyon Henderson",
  "pos": "RB",
  "team": "NE",
  "age": 23,
  "exp": 1,
  "dvs": 60.8,
  "mktValue": 3698,
  "mktPosRank": 14,
  "mktTrend30": -110,
  "starterCut": 11.49,
  "weeks": [
   {
    "w": 1,
    "team": "NE",
    "role": 11.4,
    "prod": 11.1,
    "tgt": 6,
    "car": 5,
    "air": -19
   },
   {
    "w": 2,
    "team": "NE",
    "role": 4.28,
    "prod": 6.0,
    "tgt": 2,
    "car": 3,
    "air": 2
   },
   {
    "w": 3,
    "team": "NE",
    "role": 10.05,
    "prod": 7.7,
    "tgt": 3,
    "car": 11,
    "air": 2
   },
   {
    "w": 4,
    "team": "NE",
    "role": 7.0,
    "prod": 12.6,
    "tgt": 2,
    "car": 7,
    "air": -6
   },
   {
    "w": 5,
    "team": "NE",
    "role": 7.49,
    "prod": 4.7,
    "tgt": 3,
    "car": 6,
    "air": -3
   },
   {
    "w": 6,
    "team": "NE",
    "role": 7.56,
    "prod": 4.6,
    "tgt": 2,
    "car": 9,
    "air": -4
   },
   {
    "w": 7,
    "team": "NE",
    "role": 0.87,
    "prod": 0.5,
    "tgt": 0,
    "car": 2,
    "air": 0
   },
   {
    "w": 8,
    "team": "NE",
    "role": 6.23,
    "prod": 5.5,
    "tgt": 0,
    "car": 10,
    "air": 0
   },
   {
    "w": 9,
    "team": "NE",
    "role": 16.51,
    "prod": 12.7,
    "tgt": 6,
    "car": 14,
    "air": -6
   },
   {
    "w": 10,
    "team": "NE",
    "role": 14.23,
    "prod": 28.0,
    "tgt": 1,
    "car": 14,
    "air": -5
   },
   {
    "w": 11,
    "team": "NE",
    "role": 21.29,
    "prod": 32.3,
    "tgt": 5,
    "car": 19,
    "air": 13
   },
   {
    "w": 12,
    "team": "NE",
    "role": 19.94,
    "prod": 11.1,
    "tgt": 4,
    "car": 18,
    "air": 7
   },
   {
    "w": 13,
    "team": "NE",
    "role": 14.24,
    "prod": 11.6,
    "tgt": 4,
    "car": 11,
    "air": -4
   },
   {
    "w": 15,
    "team": "NE",
    "role": 13.3,
    "prod": 30.1,
    "tgt": 3,
    "car": 14,
    "air": 20
   },
   {
    "w": 16,
    "team": "NE",
    "role": 4.0,
    "prod": 2.2,
    "tgt": 1,
    "car": 5,
    "air": 2
   },
   {
    "w": 17,
    "team": "NE",
    "role": 16.42,
    "prod": 8.2,
    "tgt": 0,
    "car": 19,
    "air": 0
   },
   {
    "w": 18,
    "team": "NE",
    "role": 11.36,
    "prod": 17.3,
    "tgt": 0,
    "car": 13,
    "air": 0
   }
  ],
  "roleFirst": 6.86,
  "roleLast6": 13.21,
  "roleChange": 6.35,
  "roleChangePctile": 0.957,
  "roleSeason": 10.95,
  "prodSeason": 12.13,
  "fpoe": 20.0,
  "teams2025": [
   "NE"
  ]
 },
 {
  "sleeperId": "12540",
  "name": "Chimere Dike",
  "pos": "WR",
  "team": "TEN",
  "age": 24,
  "exp": 1,
  "dvs": 55.3,
  "mktValue": 792,
  "mktPosRank": 93,
  "mktTrend30": -106,
  "starterCut": 11.31,
  "weeks": [
   {
    "w": 1,
    "team": "TEN",
    "role": 2.79,
    "prod": 0.9,
    "tgt": 1,
    "car": 1,
    "air": 20
   },
   {
    "w": 2,
    "team": "TEN",
    "role": 9.83,
    "prod": 2.8,
    "tgt": 5,
    "car": 2,
    "air": 38
   },
   {
    "w": 3,
    "team": "TEN",
    "role": 9.71,
    "prod": 3.5,
    "tgt": 4,
    "car": 2,
    "air": -6
   },
   {
    "w": 4,
    "team": "TEN",
    "role": 0.66,
    "prod": -0.4,
    "tgt": 0,
    "car": 1,
    "air": 0
   },
   {
    "w": 5,
    "team": "TEN",
    "role": 8.09,
    "prod": 3.7,
    "tgt": 5,
    "car": 0,
    "air": 95
   },
   {
    "w": 6,
    "team": "TEN",
    "role": 4.24,
    "prod": 2.8,
    "tgt": 3,
    "car": 0,
    "air": 2
   },
   {
    "w": 7,
    "team": "TEN",
    "role": 6.99,
    "prod": 16.9,
    "tgt": 4,
    "car": 1,
    "air": 57
   },
   {
    "w": 8,
    "team": "TEN",
    "role": 12.81,
    "prod": 16.4,
    "tgt": 8,
    "car": 1,
    "air": 65
   },
   {
    "w": 9,
    "team": "TEN",
    "role": 5.55,
    "prod": 1.5,
    "tgt": 3,
    "car": 0,
    "air": 6
   },
   {
    "w": 11,
    "team": "TEN",
    "role": 4.04,
    "prod": 3.4,
    "tgt": 3,
    "car": 0,
    "air": 10
   },
   {
    "w": 12,
    "team": "TEN",
    "role": 12.77,
    "prod": 15.4,
    "tgt": 7,
    "car": 0,
    "air": 54
   },
   {
    "w": 13,
    "team": "TEN",
    "role": 7.3,
    "prod": 1.9,
    "tgt": 4,
    "car": 1,
    "air": 35
   },
   {
    "w": 14,
    "team": "TEN",
    "role": 12.42,
    "prod": 13.4,
    "tgt": 8,
    "car": 0,
    "air": 78
   },
   {
    "w": 15,
    "team": "TEN",
    "role": 9.55,
    "prod": 5.0,
    "tgt": 5,
    "car": 1,
    "air": 1
   },
   {
    "w": 16,
    "team": "TEN",
    "role": 9.53,
    "prod": 13.0,
    "tgt": 5,
    "car": 0,
    "air": 64
   },
   {
    "w": 17,
    "team": "TEN",
    "role": 8.17,
    "prod": 10.2,
    "tgt": 5,
    "car": 1,
    "air": 63
   },
   {
    "w": 18,
    "team": "TEN",
    "role": 5.12,
    "prod": 5.7,
    "tgt": 4,
    "car": 0,
    "air": 17
   }
  ],
  "roleFirst": 6.89,
  "roleLast6": 8.68,
  "roleChange": 1.79,
  "roleChangePctile": 0.779,
  "roleSeason": 7.62,
  "prodSeason": 6.83,
  "fpoe": -13.5,
  "teams2025": [
   "TEN"
  ]
 },
 {
  "sleeperId": "12547",
  "name": "Kyle Williams",
  "pos": "WR",
  "team": "NE",
  "age": 23,
  "exp": 1,
  "dvs": 37.8,
  "mktValue": 615,
  "mktPosRank": 100,
  "mktTrend30": -317,
  "starterCut": 11.31,
  "weeks": [
   {
    "w": 1,
    "team": "NE",
    "role": 1.5,
    "prod": 2.2,
    "tgt": 1,
    "car": 0,
    "air": 12
   },
   {
    "w": 3,
    "team": "NE",
    "role": 1.56,
    "prod": 1.8,
    "tgt": 1,
    "car": 0,
    "air": 7
   },
   {
    "w": 4,
    "team": "NE",
    "role": 0.68,
    "prod": -0.2,
    "tgt": 0,
    "car": 1,
    "air": 0
   },
   {
    "w": 6,
    "team": "NE",
    "role": 3.81,
    "prod": 0.0,
    "tgt": 2,
    "car": 0,
    "air": 37
   },
   {
    "w": 7,
    "team": "NE",
    "role": 1.55,
    "prod": 0.0,
    "tgt": 1,
    "car": 0,
    "air": 17
   },
   {
    "w": 9,
    "team": "NE",
    "role": 1.64,
    "prod": 0.0,
    "tgt": 1,
    "car": 0,
    "air": 11
   },
   {
    "w": 10,
    "team": "NE",
    "role": 3.94,
    "prod": 14.2,
    "tgt": 2,
    "car": 0,
    "air": 57
   },
   {
    "w": 11,
    "team": "NE",
    "role": 5.49,
    "prod": 0.0,
    "tgt": 3,
    "car": 0,
    "air": 108
   },
   {
    "w": 12,
    "team": "NE",
    "role": 1.48,
    "prod": 2.8,
    "tgt": 1,
    "car": 0,
    "air": 5
   },
   {
    "w": 13,
    "team": "NE",
    "role": 2.22,
    "prod": 10.3,
    "tgt": 1,
    "car": 0,
    "air": 33
   },
   {
    "w": 16,
    "team": "NE",
    "role": 4.64,
    "prod": 12.6,
    "tgt": 3,
    "car": 0,
    "air": 47
   },
   {
    "w": 17,
    "team": "NE",
    "role": 7.58,
    "prod": 5.0,
    "tgt": 5,
    "car": 0,
    "air": 66
   },
   {
    "w": 18,
    "team": "NE",
    "role": 0.87,
    "prod": 0.5,
    "tgt": 0,
    "car": 1,
    "air": 0
   }
  ],
  "roleFirst": 1.79,
  "roleLast6": 3.71,
  "roleChange": 1.92,
  "roleChangePctile": 0.797,
  "roleSeason": 2.84,
  "prodSeason": 3.78,
  "fpoe": 12.2,
  "teams2025": [
   "NE"
  ]
 },
 {
  "sleeperId": "13269",
  "name": "Fernando Mendoza",
  "pos": "QB",
  "team": "LV",
  "age": 22,
  "exp": 0,
  "dvs": 85.14,
  "mktValue": 3895,
  "mktPosRank": 16,
  "mktTrend30": -157,
  "starterCut": 14.55,
  "weeks": []
 },
 {
  "sleeperId": "13276",
  "name": "Omar Cooper",
  "pos": "WR",
  "team": "NYJ",
  "age": 22,
  "exp": 0,
  "dvs": 70.99,
  "mktValue": 1997,
  "mktPosRank": 43,
  "mktTrend30": -161,
  "starterCut": 11.31,
  "weeks": []
 },
 {
  "sleeperId": "13311",
  "name": "Chris Bell",
  "pos": "WR",
  "team": "MIA",
  "age": 22,
  "exp": 0,
  "dvs": 62.46,
  "mktValue": 1329,
  "mktPosRank": 66,
  "mktTrend30": -104,
  "starterCut": 11.31,
  "weeks": []
 },
 {
  "sleeperId": "13414",
  "name": "Kaelon Black",
  "pos": "RB",
  "team": "SF",
  "age": 24,
  "exp": 0,
  "dvs": 61.55,
  "mktValue": 1010,
  "mktPosRank": 61,
  "mktTrend30": 29,
  "starterCut": 11.49,
  "weeks": []
 },
 {
  "sleeperId": "7527",
  "name": "Mac Jones",
  "pos": "QB",
  "team": "SF",
  "age": 27,
  "exp": 5,
  "dvs": 56.7,
  "mktValue": 1164,
  "mktPosRank": 39,
  "mktTrend30": 43,
  "starterCut": 14.55,
  "weeks": [
   {
    "w": 2,
    "team": "SF",
    "role": 15.13,
    "prod": 23.76,
    "tgt": 0,
    "car": 6,
    "air": 0
   },
   {
    "w": 3,
    "team": "SF",
    "role": 16.68,
    "prod": 13.26,
    "tgt": 0,
    "car": 1,
    "air": 0
   },
   {
    "w": 5,
    "team": "SF",
    "role": 22.48,
    "prod": 22.18,
    "tgt": 0,
    "car": 4,
    "air": 0
   },
   {
    "w": 6,
    "team": "SF",
    "role": 18.72,
    "prod": 11.18,
    "tgt": 0,
    "car": 5,
    "air": 0
   },
   {
    "w": 7,
    "team": "SF",
    "role": 9.82,
    "prod": 5.18,
    "tgt": 0,
    "car": 5,
    "air": 0
   },
   {
    "w": 8,
    "team": "SF",
    "role": 15.41,
    "prod": 18.02,
    "tgt": 0,
    "car": 2,
    "air": 0
   },
   {
    "w": 9,
    "team": "SF",
    "role": 15.73,
    "prod": 17.8,
    "tgt": 0,
    "car": 4,
    "air": 0
   },
   {
    "w": 10,
    "team": "SF",
    "role": 18.76,
    "prod": 23.06,
    "tgt": 0,
    "car": 1,
    "air": 0
   },
   {
    "w": 11,
    "team": "SF",
    "role": -0.3,
    "prod": -0.3,
    "tgt": 0,
    "car": 3,
    "air": 0
   },
   {
    "w": 13,
    "team": "SF",
    "role": 0.08,
    "prod": 0.2,
    "tgt": 0,
    "car": 2,
    "air": 0
   },
   {
    "w": 16,
    "team": "SF",
    "role": -0.3,
    "prod": -0.3,
    "tgt": 0,
    "car": 3,
    "air": 0
   }
  ],
  "roleFirst": 16.57,
  "roleLast6": 8.23,
  "roleChange": -8.34,
  "roleChangePctile": 0.0,
  "roleSeason": 12.02,
  "prodSeason": 12.19,
  "fpoe": 1.8,
  "teams2025": [
   "SF"
  ]
 },
 {
  "sleeperId": "8146",
  "name": "Garrett Wilson",
  "pos": "WR",
  "team": "NYJ",
  "age": 25,
  "exp": 4,
  "dvs": null,
  "mktValue": 4100,
  "mktPosRank": 15,
  "mktTrend30": 36,
  "starterCut": 11.31,
  "weeks": [
   {
    "w": 1,
    "team": "NYJ",
    "role": 14.16,
    "prod": 22.5,
    "tgt": 9,
    "car": 0,
    "air": 86
   },
   {
    "w": 2,
    "team": "NYJ",
    "role": 12.52,
    "prod": 9.0,
    "tgt": 8,
    "car": 0,
    "air": 73
   },
   {
    "w": 3,
    "team": "NYJ",
    "role": 18.38,
    "prod": 24.4,
    "tgt": 13,
    "car": 0,
    "air": 75
   },
   {
    "w": 4,
    "team": "NYJ",
    "role": 12.78,
    "prod": 20.2,
    "tgt": 8,
    "car": 0,
    "air": 78
   },
   {
    "w": 5,
    "team": "NYJ",
    "role": 16.59,
    "prod": 19.1,
    "tgt": 10,
    "car": 0,
    "air": 135
   },
   {
    "w": 6,
    "team": "NYJ",
    "role": 10.92,
    "prod": 4.3,
    "tgt": 8,
    "car": 0,
    "air": 38
   },
   {
    "w": 10,
    "team": "NYJ",
    "role": 4.57,
    "prod": 0.0,
    "tgt": 3,
    "car": 0,
    "air": 50
   }
  ]
 },
 {
  "sleeperId": "9484",
  "name": "Tucker Kraft",
  "pos": "TE",
  "team": "GB",
  "age": 25,
  "exp": 3,
  "dvs": 100.0,
  "mktValue": 3590,
  "mktPosRank": 5,
  "mktTrend30": 132,
  "starterCut": 9.63,
  "weeks": [
   {
    "w": 1,
    "team": "GB",
    "role": 8.61,
    "prod": 9.9,
    "tgt": 4,
    "car": 1,
    "air": 51
   },
   {
    "w": 2,
    "team": "GB",
    "role": 13.34,
    "prod": 24.4,
    "tgt": 7,
    "car": 0,
    "air": 56
   },
   {
    "w": 3,
    "team": "GB",
    "role": 5.51,
    "prod": 5.9,
    "tgt": 4,
    "car": 0,
    "air": 0
   },
   {
    "w": 4,
    "team": "GB",
    "role": 8.2,
    "prod": 10.6,
    "tgt": 5,
    "car": 0,
    "air": 1
   },
   {
    "w": 6,
    "team": "GB",
    "role": 3.55,
    "prod": 12.3,
    "tgt": 2,
    "car": 0,
    "air": 24
   },
   {
    "w": 7,
    "team": "GB",
    "role": 16.38,
    "prod": 16.8,
    "tgt": 10,
    "car": 0,
    "air": 36
   },
   {
    "w": 8,
    "team": "GB",
    "role": 11.91,
    "prod": 33.3,
    "tgt": 9,
    "car": 0,
    "air": 17
   },
   {
    "w": 9,
    "team": "GB",
    "role": 3.61,
    "prod": 4.0,
    "tgt": 3,
    "car": 0,
    "air": 16
   }
  ]
 },
 {
  "sleeperId": "9487",
  "name": "Parker Washington",
  "pos": "WR",
  "team": "JAX",
  "age": 24,
  "exp": 3,
  "dvs": 73.8,
  "mktValue": 2579,
  "mktPosRank": 30,
  "mktTrend30": 496,
  "starterCut": 11.31,
  "weeks": [
   {
    "w": 2,
    "team": "JAX",
    "role": 8.71,
    "prod": 12.6,
    "tgt": 5,
    "car": 0,
    "air": 33
   },
   {
    "w": 3,
    "team": "JAX",
    "role": 19.54,
    "prod": 7.4,
    "tgt": 11,
    "car": 0,
    "air": 137
   },
   {
    "w": 4,
    "team": "JAX",
    "role": 5.45,
    "prod": -0.1,
    "tgt": 2,
    "car": 1,
    "air": 27
   },
   {
    "w": 5,
    "team": "JAX",
    "role": 5.66,
    "prod": 9.6,
    "tgt": 3,
    "car": 0,
    "air": 12
   },
   {
    "w": 6,
    "team": "JAX",
    "role": 6.2,
    "prod": 4.9,
    "tgt": 4,
    "car": 0,
    "air": 70
   },
   {
    "w": 7,
    "team": "JAX",
    "role": 18.18,
    "prod": 10.2,
    "tgt": 10,
    "car": 3,
    "air": 202
   },
   {
    "w": 9,
    "team": "JAX",
    "role": 14.72,
    "prod": 17.0,
    "tgt": 9,
    "car": 0,
    "air": 84
   },
   {
    "w": 10,
    "team": "JAX",
    "role": 17.16,
    "prod": 11.9,
    "tgt": 7,
    "car": 2,
    "air": 38
   },
   {
    "w": 11,
    "team": "JAX",
    "role": 3.09,
    "prod": 4.0,
    "tgt": 2,
    "car": 0,
    "air": 19
   },
   {
    "w": 12,
    "team": "JAX",
    "role": 14.84,
    "prod": 18.1,
    "tgt": 7,
    "car": 0,
    "air": 69
   },
   {
    "w": 13,
    "team": "JAX",
    "role": 4.12,
    "prod": 3.6,
    "tgt": 3,
    "car": 0,
    "air": 63
   },
   {
    "w": 15,
    "team": "JAX",
    "role": 4.63,
    "prod": 8.3,
    "tgt": 3,
    "car": 0,
    "air": 53
   },
   {
    "w": 16,
    "team": "JAX",
    "role": 18.4,
    "prod": 26.5,
    "tgt": 10,
    "car": 0,
    "air": 134
   },
   {
    "w": 17,
    "team": "JAX",
    "role": 19.03,
    "prod": 19.0,
    "tgt": 10,
    "car": 1,
    "air": 114
   },
   {
    "w": 18,
    "team": "JAX",
    "role": 17.84,
    "prod": 19.7,
    "tgt": 9,
    "car": 0,
    "air": 132
   }
  ],
  "roleFirst": 11.21,
  "roleLast6": 13.14,
  "roleChange": 1.93,
  "roleChangePctile": 0.801,
  "roleSeason": 11.84,
  "prodSeason": 11.51,
  "fpoe": -4.9,
  "teams2025": [
   "JAX"
  ]
 },
 {
  "sleeperId": "9502",
  "name": "Tank Dell",
  "pos": "WR",
  "team": "HOU",
  "age": 26,
  "exp": 3,
  "dvs": null,
  "mktValue": 1232,
  "mktPosRank": 72,
  "mktTrend30": 40,
  "starterCut": 11.31,
  "weeks": []
 }
];
