// GENERATED by proposals/018-what-repeats/build.py — do not hand-edit.
export const META = {
 "season": 2025,
 "marketCapture": "2026-08-08",
 "modelCapture": "2026-08-08",
 "snapshot": "2026-06-23T13:17:20.007866+00:00",
 "minGames": 10,
 "positions": [
  "RB",
  "WR",
  "TE"
 ],
 "starterCuts": {
  "QB": 14.55,
  "RB": 11.49,
  "WR": 11.31,
  "TE": 9.63
 },
 "populationN": 203,
 "repeatability": {
  "seasons": [
   "2018",
   "2025"
  ],
  "n": 1154,
  "roleR": 0.767,
  "effR": 0.195,
  "top": {
   "n": 231,
   "was": 2.15,
   "became": 0.55,
   "shareFell": 0.823
  },
  "bottom": {
   "n": 231,
   "was": -1.65,
   "became": -0.2,
   "shareRose": 0.896
  },
  "keep": 0.194,
  "quintiles": {
   "role": [
    {
     "fifth": 1,
     "n": 231,
     "was": 4.22,
     "became": 5.65
    },
    {
     "fifth": 2,
     "n": 231,
     "was": 6.92,
     "became": 7.11
    },
    {
     "fifth": 3,
     "n": 230,
     "was": 9.53,
     "became": 9.07
    },
    {
     "fifth": 4,
     "n": 231,
     "was": 12.32,
     "became": 11.81
    },
    {
     "fifth": 5,
     "n": 231,
     "was": 16.54,
     "became": 14.86
    }
   ],
   "eff": [
    {
     "fifth": 1,
     "n": 231,
     "was": -1.65,
     "became": -0.2
    },
    {
     "fifth": 2,
     "n": 231,
     "was": -0.52,
     "became": -0.19
    },
    {
     "fifth": 3,
     "n": 230,
     "was": 0.12,
     "became": 0.06
    },
    {
     "fifth": 4,
     "n": 231,
     "was": 0.74,
     "became": 0.09
    },
    {
     "fifth": 5,
     "n": 231,
     "was": 2.15,
     "became": 0.55
    }
   ]
  }
 },
 "premiumBeta": 0.125,
 "premiumT": 2.7,
 "scoring": "PPR, verified by magnitude against known 2025 totals"
};
export const PLAYERS = [
 {
  "tier": "partial",
  "sleeperId": "9484",
  "name": "Tucker Kraft",
  "pos": "TE",
  "age": 25,
  "exp": 3,
  "team": "GB",
  "games": 8,
  "role": 8.89,
  "prod": 14.65,
  "fpoe": 5.76,
  "fpoePctile": null,
  "effNext": null,
  "starterCut": 9.63,
  "mktValue": 3454.0,
  "mktPosRank": 5,
  "dvs": 100.0,
  "premium": null,
  "weeks": [
   {
    "w": 1,
    "team": "GB",
    "role": 8.61,
    "prod": 9.9,
    "tgt": 4,
    "car": 1
   },
   {
    "w": 2,
    "team": "GB",
    "role": 13.34,
    "prod": 24.4,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 3,
    "team": "GB",
    "role": 5.51,
    "prod": 5.9,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 4,
    "team": "GB",
    "role": 8.2,
    "prod": 10.6,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 6,
    "team": "GB",
    "role": 3.55,
    "prod": 12.3,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 7,
    "team": "GB",
    "role": 16.38,
    "prod": 16.8,
    "tgt": 10,
    "car": 0
   },
   {
    "w": 8,
    "team": "GB",
    "role": 11.91,
    "prod": 33.3,
    "tgt": 9,
    "car": 0
   },
   {
    "w": 9,
    "team": "GB",
    "role": 3.61,
    "prod": 4.0,
    "tgt": 3,
    "car": 0
   }
  ],
  "jobRank": null,
  "priceRank": null,
  "poolSize": null,
  "modelRank": null,
  "modelPool": null
 },
 {
  "tier": "full",
  "sleeperId": "12519",
  "name": "Luther Burden III",
  "pos": "WR",
  "age": 22,
  "exp": 1,
  "team": "CHI",
  "games": 15,
  "role": 6.69,
  "prod": 8.53,
  "fpoe": 1.84,
  "fpoePctile": 0.911,
  "effNext": 0.36,
  "starterCut": 11.31,
  "mktValue": 3837.0,
  "mktPosRank": 17,
  "dvs": 63.3,
  "premium": 1.018,
  "weeks": [
   {
    "w": 1,
    "team": "CHI",
    "role": 1.4,
    "prod": 0.7,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 2,
    "team": "CHI",
    "role": 3.42,
    "prod": 1.5,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 3,
    "team": "CHI",
    "role": 7.82,
    "prod": 19.8,
    "tgt": 3,
    "car": 1
   },
   {
    "w": 4,
    "team": "CHI",
    "role": 2.92,
    "prod": 1.6,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 6,
    "team": "CHI",
    "role": 5.85,
    "prod": 9.1,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 7,
    "team": "CHI",
    "role": 4.96,
    "prod": 3.1,
    "tgt": 2,
    "car": 1
   },
   {
    "w": 8,
    "team": "CHI",
    "role": 1.34,
    "prod": 0.9,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 10,
    "team": "CHI",
    "role": 5.3,
    "prod": 8.1,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 11,
    "team": "CHI",
    "role": 7.84,
    "prod": 5.7,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 12,
    "team": "CHI",
    "role": 8.65,
    "prod": 9.1,
    "tgt": 5,
    "car": 1
   },
   {
    "w": 13,
    "team": "CHI",
    "role": 9.95,
    "prod": 7.6,
    "tgt": 6,
    "car": 1
   },
   {
    "w": 14,
    "team": "CHI",
    "role": 9.59,
    "prod": 11.0,
    "tgt": 6,
    "car": 1
   },
   {
    "w": 15,
    "team": "CHI",
    "role": 10.23,
    "prod": 14.4,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 17,
    "team": "CHI",
    "role": 14.5,
    "prod": 27.8,
    "tgt": 9,
    "car": 0
   },
   {
    "w": 18,
    "team": "CHI",
    "role": 6.53,
    "prod": 7.5,
    "tgt": 4,
    "car": 1
   }
  ],
  "jobRank": 65,
  "priceRank": 14,
  "poolSize": 93,
  "modelRank": 42,
  "modelPool": 93
 },
 {
  "tier": "partial",
  "sleeperId": "8146",
  "name": "Garrett Wilson",
  "pos": "WR",
  "age": 25,
  "exp": 4,
  "team": "NYJ",
  "games": 7,
  "role": 12.85,
  "prod": 14.21,
  "fpoe": 1.37,
  "fpoePctile": null,
  "effNext": null,
  "starterCut": 11.31,
  "mktValue": 4180.0,
  "mktPosRank": 14,
  "dvs": null,
  "premium": null,
  "weeks": [
   {
    "w": 1,
    "team": "NYJ",
    "role": 14.16,
    "prod": 22.5,
    "tgt": 9,
    "car": 0
   },
   {
    "w": 2,
    "team": "NYJ",
    "role": 12.52,
    "prod": 9.0,
    "tgt": 8,
    "car": 0
   },
   {
    "w": 3,
    "team": "NYJ",
    "role": 18.38,
    "prod": 24.4,
    "tgt": 13,
    "car": 0
   },
   {
    "w": 4,
    "team": "NYJ",
    "role": 12.78,
    "prod": 20.2,
    "tgt": 8,
    "car": 0
   },
   {
    "w": 5,
    "team": "NYJ",
    "role": 16.59,
    "prod": 19.1,
    "tgt": 10,
    "car": 0
   },
   {
    "w": 6,
    "team": "NYJ",
    "role": 10.92,
    "prod": 4.3,
    "tgt": 8,
    "car": 0
   },
   {
    "w": 10,
    "team": "NYJ",
    "role": 4.57,
    "prod": 0.0,
    "tgt": 3,
    "car": 0
   }
  ],
  "jobRank": null,
  "priceRank": null,
  "poolSize": null,
  "modelRank": null,
  "modelPool": null
 },
 {
  "tier": "full",
  "sleeperId": "11603",
  "name": "AJ Barner",
  "pos": "TE",
  "age": 24,
  "exp": 2,
  "team": "SEA",
  "games": 17,
  "role": 7.37,
  "prod": 8.66,
  "fpoe": 1.3,
  "fpoePctile": 0.862,
  "effNext": 0.25,
  "starterCut": 9.63,
  "mktValue": 1544.0,
  "mktPosRank": 20,
  "dvs": 86.9,
  "premium": 0.267,
  "weeks": [
   {
    "w": 1,
    "team": "SEA",
    "role": 2.82,
    "prod": 1.2,
    "tgt": 2,
    "car": 1
   },
   {
    "w": 2,
    "team": "SEA",
    "role": 7.07,
    "prod": 10.8,
    "tgt": 3,
    "car": 1
   },
   {
    "w": 3,
    "team": "SEA",
    "role": 2.28,
    "prod": 3.3,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 4,
    "team": "SEA",
    "role": 7.38,
    "prod": 12.2,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 5,
    "team": "SEA",
    "role": 13.57,
    "prod": 24.3,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 6,
    "team": "SEA",
    "role": 5.37,
    "prod": 10.1,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 7,
    "team": "SEA",
    "role": 4.95,
    "prod": 1.9,
    "tgt": 3,
    "car": 1
   },
   {
    "w": 9,
    "team": "SEA",
    "role": 12.04,
    "prod": 11.5,
    "tgt": 4,
    "car": 1
   },
   {
    "w": 10,
    "team": "SEA",
    "role": 0.59,
    "prod": 0.3,
    "tgt": 0,
    "car": 2
   },
   {
    "w": 11,
    "team": "SEA",
    "role": 17.78,
    "prod": 17.1,
    "tgt": 11,
    "car": 2
   },
   {
    "w": 12,
    "team": "SEA",
    "role": 8.57,
    "prod": 3.8,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 13,
    "team": "SEA",
    "role": 7.9,
    "prod": 7.7,
    "tgt": 5,
    "car": 1
   },
   {
    "w": 14,
    "team": "SEA",
    "role": 9.73,
    "prod": 5.7,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 15,
    "team": "SEA",
    "role": 6.87,
    "prod": 5.7,
    "tgt": 6,
    "car": 0
   },
   {
    "w": 16,
    "team": "SEA",
    "role": 10.1,
    "prod": 15.0,
    "tgt": 6,
    "car": 1
   },
   {
    "w": 17,
    "team": "SEA",
    "role": 4.01,
    "prod": 13.3,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 18,
    "team": "SEA",
    "role": 4.19,
    "prod": 3.4,
    "tgt": 3,
    "car": 0
   }
  ],
  "jobRank": 23,
  "priceRank": 16,
  "poolSize": 44,
  "modelRank": 15,
  "modelPool": 44
 },
 {
  "tier": "full",
  "sleeperId": "12529",
  "name": "TreVeyon Henderson",
  "pos": "RB",
  "age": 23,
  "exp": 1,
  "team": "NE",
  "games": 17,
  "role": 10.95,
  "prod": 12.13,
  "fpoe": 1.18,
  "fpoePctile": 0.847,
  "effNext": 0.23,
  "starterCut": 11.49,
  "mktValue": 3598.0,
  "mktPosRank": 15,
  "dvs": 60.8,
  "premium": 0.33,
  "weeks": [
   {
    "w": 1,
    "team": "NE",
    "role": 11.4,
    "prod": 11.1,
    "tgt": 6,
    "car": 5
   },
   {
    "w": 2,
    "team": "NE",
    "role": 4.28,
    "prod": 6.0,
    "tgt": 2,
    "car": 3
   },
   {
    "w": 3,
    "team": "NE",
    "role": 10.05,
    "prod": 7.7,
    "tgt": 3,
    "car": 11
   },
   {
    "w": 4,
    "team": "NE",
    "role": 7.0,
    "prod": 12.6,
    "tgt": 2,
    "car": 7
   },
   {
    "w": 5,
    "team": "NE",
    "role": 7.49,
    "prod": 4.7,
    "tgt": 3,
    "car": 6
   },
   {
    "w": 6,
    "team": "NE",
    "role": 7.56,
    "prod": 4.6,
    "tgt": 2,
    "car": 9
   },
   {
    "w": 7,
    "team": "NE",
    "role": 0.87,
    "prod": 0.5,
    "tgt": 0,
    "car": 2
   },
   {
    "w": 8,
    "team": "NE",
    "role": 6.23,
    "prod": 5.5,
    "tgt": 0,
    "car": 10
   },
   {
    "w": 9,
    "team": "NE",
    "role": 16.51,
    "prod": 12.7,
    "tgt": 6,
    "car": 14
   },
   {
    "w": 10,
    "team": "NE",
    "role": 14.23,
    "prod": 28.0,
    "tgt": 1,
    "car": 14
   },
   {
    "w": 11,
    "team": "NE",
    "role": 21.29,
    "prod": 32.3,
    "tgt": 5,
    "car": 19
   },
   {
    "w": 12,
    "team": "NE",
    "role": 19.94,
    "prod": 11.1,
    "tgt": 4,
    "car": 18
   },
   {
    "w": 13,
    "team": "NE",
    "role": 14.24,
    "prod": 11.6,
    "tgt": 4,
    "car": 11
   },
   {
    "w": 15,
    "team": "NE",
    "role": 13.3,
    "prod": 30.1,
    "tgt": 3,
    "car": 14
   },
   {
    "w": 16,
    "team": "NE",
    "role": 4.0,
    "prod": 2.2,
    "tgt": 1,
    "car": 5
   },
   {
    "w": 17,
    "team": "NE",
    "role": 16.42,
    "prod": 8.2,
    "tgt": 0,
    "car": 19
   },
   {
    "w": 18,
    "team": "NE",
    "role": 11.36,
    "prod": 17.3,
    "tgt": 0,
    "car": 13
   }
  ],
  "jobRank": 29,
  "priceRank": 13,
  "poolSize": 66,
  "modelRank": 23,
  "modelPool": 66
 },
 {
  "tier": "full",
  "sleeperId": "12547",
  "name": "Kyle Williams",
  "pos": "WR",
  "age": 23,
  "exp": 1,
  "team": "NE",
  "games": 13,
  "role": 2.84,
  "prod": 3.78,
  "fpoe": 0.94,
  "fpoePctile": 0.813,
  "effNext": 0.18,
  "starterCut": 11.31,
  "mktValue": 595.0,
  "mktPosRank": 100,
  "dvs": 37.8,
  "premium": 0.501,
  "weeks": [
   {
    "w": 1,
    "team": "NE",
    "role": 1.5,
    "prod": 2.2,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 3,
    "team": "NE",
    "role": 1.56,
    "prod": 1.8,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 4,
    "team": "NE",
    "role": 0.68,
    "prod": -0.2,
    "tgt": 0,
    "car": 1
   },
   {
    "w": 6,
    "team": "NE",
    "role": 3.81,
    "prod": 0.0,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 7,
    "team": "NE",
    "role": 1.55,
    "prod": 0.0,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 9,
    "team": "NE",
    "role": 1.64,
    "prod": 0.0,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 10,
    "team": "NE",
    "role": 3.94,
    "prod": 14.2,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 11,
    "team": "NE",
    "role": 5.49,
    "prod": 0.0,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 12,
    "team": "NE",
    "role": 1.48,
    "prod": 2.8,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 13,
    "team": "NE",
    "role": 2.22,
    "prod": 10.3,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 16,
    "team": "NE",
    "role": 4.64,
    "prod": 12.6,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 17,
    "team": "NE",
    "role": 7.58,
    "prod": 5.0,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 18,
    "team": "NE",
    "role": 0.87,
    "prod": 0.5,
    "tgt": 0,
    "car": 1
   }
  ],
  "jobRank": 91,
  "priceRank": 67,
  "poolSize": 93,
  "modelRank": 78,
  "modelPool": 93
 },
 {
  "tier": "partial",
  "sleeperId": "11570",
  "name": "Rasheen Ali",
  "pos": "RB",
  "age": 25,
  "exp": 2,
  "team": "BAL",
  "games": 8,
  "role": 2.46,
  "prod": 3.02,
  "fpoe": 0.56,
  "fpoePctile": null,
  "effNext": null,
  "starterCut": 11.49,
  "mktValue": 28.0,
  "mktPosRank": 108,
  "dvs": 20.7,
  "premium": null,
  "weeks": [
   {
    "w": 1,
    "team": "BAL",
    "role": 0.64,
    "prod": 0.5,
    "tgt": 0,
    "car": 1
   },
   {
    "w": 11,
    "team": "BAL",
    "role": 1.29,
    "prod": 2.5,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 13,
    "team": "BAL",
    "role": 2.45,
    "prod": 1.7,
    "tgt": 0,
    "car": 4
   },
   {
    "w": 14,
    "team": "BAL",
    "role": 5.11,
    "prod": 3.3,
    "tgt": 3,
    "car": 1
   },
   {
    "w": 15,
    "team": "BAL",
    "role": 2.96,
    "prod": 11.2,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 16,
    "team": "BAL",
    "role": 2.85,
    "prod": 2.2,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 17,
    "team": "BAL",
    "role": 3.89,
    "prod": 2.8,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 18,
    "team": "BAL",
    "role": 0.52,
    "prod": 0.0,
    "tgt": 0,
    "car": 1
   }
  ],
  "jobRank": null,
  "priceRank": null,
  "poolSize": null,
  "modelRank": null,
  "modelPool": null
 },
 {
  "tier": "full",
  "sleeperId": "11597",
  "name": "Theo Johnson",
  "pos": "TE",
  "age": 25,
  "exp": 2,
  "team": "NYG",
  "games": 15,
  "role": 8.46,
  "prod": 8.52,
  "fpoe": 0.06,
  "fpoePctile": 0.493,
  "effNext": 0.01,
  "starterCut": 9.63,
  "mktValue": 741.0,
  "mktPosRank": 35,
  "dvs": 81.1,
  "premium": -0.345,
  "weeks": [
   {
    "w": 1,
    "team": "NYG",
    "role": 3.97,
    "prod": 1.5,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 2,
    "team": "NYG",
    "role": 8.51,
    "prod": 7.4,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 3,
    "team": "NYG",
    "role": 3.45,
    "prod": 2.0,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 4,
    "team": "NYG",
    "role": 10.07,
    "prod": 10.7,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 5,
    "team": "NYG",
    "role": 15.88,
    "prod": 21.3,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 6,
    "team": "NYG",
    "role": 5.73,
    "prod": 4.7,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 7,
    "team": "NYG",
    "role": 9.77,
    "prod": 15.6,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 8,
    "team": "NYG",
    "role": 6.19,
    "prod": 5.0,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 9,
    "team": "NYG",
    "role": 9.85,
    "prod": 11.7,
    "tgt": 6,
    "car": 0
   },
   {
    "w": 10,
    "team": "NYG",
    "role": 13.31,
    "prod": 14.5,
    "tgt": 8,
    "car": 0
   },
   {
    "w": 11,
    "team": "NYG",
    "role": 5.14,
    "prod": 6.6,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 12,
    "team": "NYG",
    "role": 13.91,
    "prod": 10.7,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 13,
    "team": "NYG",
    "role": 11.93,
    "prod": 5.9,
    "tgt": 8,
    "car": 0
   },
   {
    "w": 15,
    "team": "NYG",
    "role": 5.97,
    "prod": 10.2,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 16,
    "team": "NYG",
    "role": 3.17,
    "prod": 0.0,
    "tgt": 2,
    "car": 0
   }
  ],
  "jobRank": 18,
  "priceRank": 28,
  "poolSize": 44,
  "modelRank": 21,
  "modelPool": 44
 },
 {
  "tier": "full",
  "sleeperId": "12509",
  "name": "Tre Harris",
  "pos": "WR",
  "age": 24,
  "exp": 1,
  "team": "LAC",
  "games": 16,
  "role": 4.34,
  "prod": 4.34,
  "fpoe": -0.0,
  "fpoePctile": 0.443,
  "effNext": -0.0,
  "starterCut": 11.31,
  "mktValue": 1312.0,
  "mktPosRank": 68,
  "dvs": 43.1,
  "premium": 0.86,
  "weeks": [
   {
    "w": 1,
    "team": "LAC",
    "role": 1.49,
    "prod": 2.1,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 2,
    "team": "LAC",
    "role": 4.94,
    "prod": 5.4,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 3,
    "team": "LAC",
    "role": 1.44,
    "prod": 0.0,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 4,
    "team": "LAC",
    "role": 1.25,
    "prod": 0.0,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 6,
    "team": "LAC",
    "role": 8.25,
    "prod": 6.7,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 7,
    "team": "LAC",
    "role": 3.5,
    "prod": 4.3,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 8,
    "team": "LAC",
    "role": 5.59,
    "prod": 8.8,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 9,
    "team": "LAC",
    "role": 3.05,
    "prod": 3.8,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 10,
    "team": "LAC",
    "role": 2.87,
    "prod": 2.4,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 11,
    "team": "LAC",
    "role": 1.4,
    "prod": 2.2,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 13,
    "team": "LAC",
    "role": 6.33,
    "prod": 6.0,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 14,
    "team": "LAC",
    "role": 3.93,
    "prod": 3.1,
    "tgt": 2,
    "car": 1
   },
   {
    "w": 15,
    "team": "LAC",
    "role": 6.91,
    "prod": 7.9,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 16,
    "team": "LAC",
    "role": 8.0,
    "prod": 9.4,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 17,
    "team": "LAC",
    "role": 2.36,
    "prod": 2.5,
    "tgt": 1,
    "car": 1
   },
   {
    "w": 18,
    "team": "LAC",
    "role": 8.15,
    "prod": 4.8,
    "tgt": 6,
    "car": 0
   }
  ],
  "jobRank": 86,
  "priceRank": 48,
  "poolSize": 93,
  "modelRank": 66,
  "modelPool": 93
 },
 {
  "tier": "full",
  "sleeperId": "12527",
  "name": "Ashton Jeanty",
  "pos": "RB",
  "age": 22,
  "exp": 1,
  "team": "LV",
  "games": 17,
  "role": 14.64,
  "prod": 14.42,
  "fpoe": -0.23,
  "fpoePctile": 0.36,
  "effNext": -0.04,
  "starterCut": 11.49,
  "mktValue": 6941.0,
  "mktPosRank": 3,
  "dvs": 75.3,
  "premium": 0.008,
  "weeks": [
   {
    "w": 1,
    "team": "LV",
    "role": 12.9,
    "prod": 12.0,
    "tgt": 2,
    "car": 19
   },
   {
    "w": 2,
    "team": "LV",
    "role": 10.93,
    "prod": 7.4,
    "tgt": 4,
    "car": 11
   },
   {
    "w": 3,
    "team": "LV",
    "role": 8.54,
    "prod": 6.3,
    "tgt": 0,
    "car": 17
   },
   {
    "w": 4,
    "team": "LV",
    "role": 17.44,
    "prod": 33.5,
    "tgt": 2,
    "car": 21
   },
   {
    "w": 5,
    "team": "LV",
    "role": 16.84,
    "prod": 15.9,
    "tgt": 7,
    "car": 14
   },
   {
    "w": 6,
    "team": "LV",
    "role": 23.04,
    "prod": 16.6,
    "tgt": 4,
    "car": 23
   },
   {
    "w": 7,
    "team": "LV",
    "role": 4.15,
    "prod": 4.4,
    "tgt": 1,
    "car": 6
   },
   {
    "w": 9,
    "team": "LV",
    "role": 18.5,
    "prod": 19.9,
    "tgt": 5,
    "car": 13
   },
   {
    "w": 10,
    "team": "LV",
    "role": 15.86,
    "prod": 15.3,
    "tgt": 5,
    "car": 19
   },
   {
    "w": 11,
    "team": "LV",
    "role": 13.47,
    "prod": 9.4,
    "tgt": 8,
    "car": 6
   },
   {
    "w": 12,
    "team": "LV",
    "role": 20.34,
    "prod": 24.8,
    "tgt": 8,
    "car": 17
   },
   {
    "w": 13,
    "team": "LV",
    "role": 20.14,
    "prod": 12.1,
    "tgt": 8,
    "car": 15
   },
   {
    "w": 14,
    "team": "LV",
    "role": 9.95,
    "prod": 5.8,
    "tgt": 4,
    "car": 10
   },
   {
    "w": 15,
    "team": "LV",
    "role": 11.32,
    "prod": 8.2,
    "tgt": 6,
    "car": 9
   },
   {
    "w": 16,
    "team": "LV",
    "role": 13.63,
    "prod": 31.8,
    "tgt": 2,
    "car": 24
   },
   {
    "w": 17,
    "team": "LV",
    "role": 11.7,
    "prod": 9.3,
    "tgt": 2,
    "car": 16
   },
   {
    "w": 18,
    "team": "LV",
    "role": 20.21,
    "prod": 12.4,
    "tgt": 5,
    "car": 26
   }
  ],
  "jobRank": 12,
  "priceRank": 3,
  "poolSize": 66,
  "modelRank": 16,
  "modelPool": 66
 },
 {
  "tier": "full",
  "sleeperId": "9487",
  "name": "Parker Washington",
  "pos": "WR",
  "age": 24,
  "exp": 3,
  "team": "JAX",
  "games": 15,
  "role": 11.84,
  "prod": 11.51,
  "fpoe": -0.32,
  "fpoePctile": 0.335,
  "effNext": -0.06,
  "starterCut": 11.31,
  "mktValue": 2513.0,
  "mktPosRank": 31,
  "dvs": 73.8,
  "premium": -0.046,
  "weeks": [
   {
    "w": 2,
    "team": "JAX",
    "role": 8.71,
    "prod": 12.6,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 3,
    "team": "JAX",
    "role": 19.54,
    "prod": 7.4,
    "tgt": 11,
    "car": 0
   },
   {
    "w": 4,
    "team": "JAX",
    "role": 5.45,
    "prod": -0.1,
    "tgt": 2,
    "car": 1
   },
   {
    "w": 5,
    "team": "JAX",
    "role": 5.66,
    "prod": 9.6,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 6,
    "team": "JAX",
    "role": 6.2,
    "prod": 4.9,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 7,
    "team": "JAX",
    "role": 18.18,
    "prod": 10.2,
    "tgt": 10,
    "car": 3
   },
   {
    "w": 9,
    "team": "JAX",
    "role": 14.72,
    "prod": 17.0,
    "tgt": 9,
    "car": 0
   },
   {
    "w": 10,
    "team": "JAX",
    "role": 17.16,
    "prod": 11.9,
    "tgt": 7,
    "car": 2
   },
   {
    "w": 11,
    "team": "JAX",
    "role": 3.09,
    "prod": 4.0,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 12,
    "team": "JAX",
    "role": 14.84,
    "prod": 18.1,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 13,
    "team": "JAX",
    "role": 4.12,
    "prod": 3.6,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 15,
    "team": "JAX",
    "role": 4.63,
    "prod": 8.3,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 16,
    "team": "JAX",
    "role": 18.4,
    "prod": 26.5,
    "tgt": 10,
    "car": 0
   },
   {
    "w": 17,
    "team": "JAX",
    "role": 19.03,
    "prod": 19.0,
    "tgt": 10,
    "car": 1
   },
   {
    "w": 18,
    "team": "JAX",
    "role": 17.84,
    "prod": 19.7,
    "tgt": 9,
    "car": 0
   }
  ],
  "jobRank": 24,
  "priceRank": 24,
  "poolSize": 93,
  "modelRank": 24,
  "modelPool": 93
 },
 {
  "tier": "full",
  "sleeperId": "12492",
  "name": "Pat Bryant",
  "pos": "WR",
  "age": 23,
  "exp": 1,
  "team": "DEN",
  "games": 12,
  "role": 6.81,
  "prod": 6.23,
  "fpoe": -0.58,
  "fpoePctile": 0.261,
  "effNext": -0.11,
  "starterCut": 11.31,
  "mktValue": 1114.0,
  "mktPosRank": 81,
  "dvs": 46.4,
  "premium": 0.186,
  "weeks": [
   {
    "w": 2,
    "team": "DEN",
    "role": 4.21,
    "prod": 3.8,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 4,
    "team": "DEN",
    "role": 3.59,
    "prod": 0.0,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 6,
    "team": "DEN",
    "role": 2.87,
    "prod": 4.2,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 7,
    "team": "DEN",
    "role": 6.09,
    "prod": 1.6,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 8,
    "team": "DEN",
    "role": 9.08,
    "prod": 12.0,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 9,
    "team": "DEN",
    "role": 5.4,
    "prod": 4.0,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 10,
    "team": "DEN",
    "role": 3.06,
    "prod": 5.3,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 11,
    "team": "DEN",
    "role": 9.46,
    "prod": 13.2,
    "tgt": 6,
    "car": 0
   },
   {
    "w": 13,
    "team": "DEN",
    "role": 10.57,
    "prod": 7.2,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 14,
    "team": "DEN",
    "role": 6.39,
    "prod": 7.2,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 16,
    "team": "DEN",
    "role": 12.33,
    "prod": 9.2,
    "tgt": 8,
    "car": 0
   },
   {
    "w": 18,
    "team": "DEN",
    "role": 8.71,
    "prod": 7.1,
    "tgt": 5,
    "car": 0
   }
  ],
  "jobRank": 64,
  "priceRank": 56,
  "poolSize": 93,
  "modelRank": 62,
  "modelPool": 93
 },
 {
  "tier": "partial",
  "sleeperId": "11576",
  "name": "Braelon Allen",
  "pos": "RB",
  "age": 22,
  "exp": 2,
  "team": "NYJ",
  "games": 4,
  "role": 4.51,
  "prod": 3.83,
  "fpoe": -0.69,
  "fpoePctile": null,
  "effNext": null,
  "starterCut": 11.49,
  "mktValue": 1157.0,
  "mktPosRank": 54,
  "dvs": null,
  "premium": null,
  "weeks": [
   {
    "w": 1,
    "team": "NYJ",
    "role": 4.47,
    "prod": 6.9,
    "tgt": 0,
    "car": 6
   },
   {
    "w": 2,
    "team": "NYJ",
    "role": 5.25,
    "prod": 1.1,
    "tgt": 1,
    "car": 2
   },
   {
    "w": 3,
    "team": "NYJ",
    "role": 6.13,
    "prod": 6.7,
    "tgt": 2,
    "car": 6
   },
   {
    "w": 4,
    "team": "NYJ",
    "role": 2.2,
    "prod": 0.6,
    "tgt": 0,
    "car": 4
   }
  ],
  "jobRank": null,
  "priceRank": null,
  "poolSize": null,
  "modelRank": null,
  "modelPool": null
 },
 {
  "tier": "full",
  "sleeperId": "12540",
  "name": "Chimere Dike",
  "pos": "WR",
  "age": 24,
  "exp": 1,
  "team": "TEN",
  "games": 17,
  "role": 7.62,
  "prod": 6.83,
  "fpoe": -0.79,
  "fpoePctile": 0.207,
  "effNext": -0.15,
  "starterCut": 11.31,
  "mktValue": 860.0,
  "mktPosRank": 91,
  "dvs": 55.3,
  "premium": -0.111,
  "weeks": [
   {
    "w": 1,
    "team": "TEN",
    "role": 2.79,
    "prod": 0.9,
    "tgt": 1,
    "car": 1
   },
   {
    "w": 2,
    "team": "TEN",
    "role": 9.83,
    "prod": 2.8,
    "tgt": 5,
    "car": 2
   },
   {
    "w": 3,
    "team": "TEN",
    "role": 9.71,
    "prod": 3.5,
    "tgt": 4,
    "car": 2
   },
   {
    "w": 4,
    "team": "TEN",
    "role": 0.66,
    "prod": -0.4,
    "tgt": 0,
    "car": 1
   },
   {
    "w": 5,
    "team": "TEN",
    "role": 8.09,
    "prod": 3.7,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 6,
    "team": "TEN",
    "role": 4.24,
    "prod": 2.8,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 7,
    "team": "TEN",
    "role": 6.99,
    "prod": 16.9,
    "tgt": 4,
    "car": 1
   },
   {
    "w": 8,
    "team": "TEN",
    "role": 12.81,
    "prod": 16.4,
    "tgt": 8,
    "car": 1
   },
   {
    "w": 9,
    "team": "TEN",
    "role": 5.55,
    "prod": 1.5,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 11,
    "team": "TEN",
    "role": 4.04,
    "prod": 3.4,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 12,
    "team": "TEN",
    "role": 12.77,
    "prod": 15.4,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 13,
    "team": "TEN",
    "role": 7.3,
    "prod": 1.9,
    "tgt": 4,
    "car": 1
   },
   {
    "w": 14,
    "team": "TEN",
    "role": 12.42,
    "prod": 13.4,
    "tgt": 8,
    "car": 0
   },
   {
    "w": 15,
    "team": "TEN",
    "role": 9.55,
    "prod": 5.0,
    "tgt": 5,
    "car": 1
   },
   {
    "w": 16,
    "team": "TEN",
    "role": 9.53,
    "prod": 13.0,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 17,
    "team": "TEN",
    "role": 8.17,
    "prod": 10.2,
    "tgt": 5,
    "car": 1
   },
   {
    "w": 18,
    "team": "TEN",
    "role": 5.12,
    "prod": 5.7,
    "tgt": 4,
    "car": 0
   }
  ],
  "jobRank": 57,
  "priceRank": 63,
  "poolSize": 93,
  "modelRank": 54,
  "modelPool": 93
 },
 {
  "tier": "full",
  "sleeperId": "11626",
  "name": "Xavier Legette",
  "pos": "WR",
  "age": 25,
  "exp": 2,
  "team": "CAR",
  "games": 15,
  "role": 7.2,
  "prod": 5.95,
  "fpoe": -1.25,
  "fpoePctile": 0.128,
  "effNext": -0.24,
  "starterCut": 11.31,
  "mktValue": 465.0,
  "mktPosRank": 105,
  "dvs": 44.2,
  "premium": -0.319,
  "weeks": [
   {
    "w": 1,
    "team": "CAR",
    "role": 12.66,
    "prod": 4.0,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 2,
    "team": "CAR",
    "role": 14.67,
    "prod": 0.8,
    "tgt": 8,
    "car": 1
   },
   {
    "w": 5,
    "team": "CAR",
    "role": 7.01,
    "prod": 11.1,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 6,
    "team": "CAR",
    "role": 2.76,
    "prod": 3.1,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 7,
    "team": "CAR",
    "role": 19.53,
    "prod": 24.2,
    "tgt": 11,
    "car": 0
   },
   {
    "w": 8,
    "team": "CAR",
    "role": 4.67,
    "prod": 3.7,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 9,
    "team": "CAR",
    "role": 5.16,
    "prod": 3.2,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 10,
    "team": "CAR",
    "role": 1.61,
    "prod": 0.0,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 11,
    "team": "CAR",
    "role": 13.8,
    "prod": 18.3,
    "tgt": 8,
    "car": 0
   },
   {
    "w": 12,
    "team": "CAR",
    "role": 7.71,
    "prod": 5.2,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 13,
    "team": "CAR",
    "role": 3.0,
    "prod": 1.1,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 15,
    "team": "CAR",
    "role": 4.2,
    "prod": 5.9,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 16,
    "team": "CAR",
    "role": 3.54,
    "prod": 2.2,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 17,
    "team": "CAR",
    "role": 1.26,
    "prod": 1.3,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 18,
    "team": "CAR",
    "role": 6.41,
    "prod": 5.2,
    "tgt": 4,
    "car": 0
   }
  ],
  "jobRank": 59,
  "priceRank": 70,
  "poolSize": 93,
  "modelRank": 64,
  "modelPool": 93
 },
 {
  "tier": "full",
  "sleeperId": "12499",
  "name": "Elic Ayomanor",
  "pos": "WR",
  "age": 23,
  "exp": 1,
  "team": "TEN",
  "games": 16,
  "role": 8.68,
  "prod": 7.28,
  "fpoe": -1.39,
  "fpoePctile": 0.103,
  "effNext": -0.27,
  "starterCut": 11.31,
  "mktValue": 990.0,
  "mktPosRank": 87,
  "dvs": 56.4,
  "premium": -0.306,
  "weeks": [
   {
    "w": 1,
    "team": "TEN",
    "role": 10.26,
    "prod": 3.3,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 2,
    "team": "TEN",
    "role": 8.72,
    "prod": 15.6,
    "tgt": 6,
    "car": 0
   },
   {
    "w": 3,
    "team": "TEN",
    "role": 10.23,
    "prod": 13.8,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 4,
    "team": "TEN",
    "role": 10.16,
    "prod": 6.4,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 5,
    "team": "TEN",
    "role": 5.52,
    "prod": 3.8,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 6,
    "team": "TEN",
    "role": 6.71,
    "prod": 5.7,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 7,
    "team": "TEN",
    "role": 6.99,
    "prod": 4.9,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 8,
    "team": "TEN",
    "role": 14.77,
    "prod": 9.2,
    "tgt": 8,
    "car": 0
   },
   {
    "w": 9,
    "team": "TEN",
    "role": 9.37,
    "prod": 7.6,
    "tgt": 6,
    "car": 0
   },
   {
    "w": 11,
    "team": "TEN",
    "role": 8.41,
    "prod": 3.1,
    "tgt": 6,
    "car": 0
   },
   {
    "w": 13,
    "team": "TEN",
    "role": 7.46,
    "prod": 1.5,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 14,
    "team": "TEN",
    "role": 4.2,
    "prod": 8.4,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 15,
    "team": "TEN",
    "role": 1.77,
    "prod": 2.7,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 16,
    "team": "TEN",
    "role": 6.58,
    "prod": 8.8,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 17,
    "team": "TEN",
    "role": 13.73,
    "prod": 13.7,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 18,
    "team": "TEN",
    "role": 13.93,
    "prod": 8.0,
    "tgt": 10,
    "car": 0
   }
  ],
  "jobRank": 48,
  "priceRank": 59,
  "poolSize": 93,
  "modelRank": 52,
  "modelPool": 93
 },
 {
  "tier": "full",
  "sleeperId": "11625",
  "name": "Adonai Mitchell",
  "pos": "WR",
  "age": 23,
  "exp": 2,
  "team": "NYJ",
  "games": 16,
  "role": 7.26,
  "prod": 5.49,
  "fpoe": -1.76,
  "fpoePctile": 0.054,
  "effNext": -0.34,
  "starterCut": 11.31,
  "mktValue": 1183.0,
  "mktPosRank": 75,
  "dvs": 40.1,
  "premium": 0.171,
  "weeks": [
   {
    "w": 1,
    "team": "IND",
    "role": 3.49,
    "prod": 4.1,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 2,
    "team": "IND",
    "role": 9.07,
    "prod": 4.0,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 3,
    "team": "IND",
    "role": 2.73,
    "prod": 0.0,
    "tgt": 2,
    "car": 0
   },
   {
    "w": 4,
    "team": "IND",
    "role": 7.42,
    "prod": 10.6,
    "tgt": 4,
    "car": 0
   },
   {
    "w": 5,
    "team": "IND",
    "role": 2.22,
    "prod": 0.0,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 7,
    "team": "IND",
    "role": 1.49,
    "prod": 1.8,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 8,
    "team": "IND",
    "role": 1.57,
    "prod": 0.0,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 9,
    "team": "IND",
    "role": 1.5,
    "prod": 1.7,
    "tgt": 1,
    "car": 0
   },
   {
    "w": 11,
    "team": "NYJ",
    "role": 8.97,
    "prod": 2.0,
    "tgt": 6,
    "car": 0
   },
   {
    "w": 12,
    "team": "NYJ",
    "role": 12.03,
    "prod": 6.2,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 13,
    "team": "NYJ",
    "role": 19.11,
    "prod": 24.2,
    "tgt": 12,
    "car": 0
   },
   {
    "w": 14,
    "team": "NYJ",
    "role": 9.59,
    "prod": 3.4,
    "tgt": 6,
    "car": 0
   },
   {
    "w": 15,
    "team": "NYJ",
    "role": 13.46,
    "prod": 17.4,
    "tgt": 9,
    "car": 1
   },
   {
    "w": 16,
    "team": "NYJ",
    "role": 7.87,
    "prod": 7.3,
    "tgt": 6,
    "car": 0
   },
   {
    "w": 17,
    "team": "NYJ",
    "role": 11.89,
    "prod": 5.2,
    "tgt": 9,
    "car": 0
   },
   {
    "w": 18,
    "team": "NYJ",
    "role": 3.73,
    "prod": 0.0,
    "tgt": 3,
    "car": 0
   }
  ],
  "jobRank": 58,
  "priceRank": 52,
  "poolSize": 93,
  "modelRank": 72,
  "modelPool": 93
 },
 {
  "tier": "full",
  "sleeperId": "11620",
  "name": "Rome Odunze",
  "pos": "WR",
  "age": 24,
  "exp": 2,
  "team": "CHI",
  "games": 12,
  "role": 14.37,
  "prod": 12.01,
  "fpoe": -2.36,
  "fpoePctile": 0.03,
  "effNext": -0.46,
  "starterCut": 11.31,
  "mktValue": 3167.0,
  "mktPosRank": 25,
  "dvs": 69.0,
  "premium": -0.367,
  "weeks": [
   {
    "w": 1,
    "team": "CHI",
    "role": 15.98,
    "prod": 13.7,
    "tgt": 9,
    "car": 0
   },
   {
    "w": 2,
    "team": "CHI",
    "role": 22.72,
    "prod": 31.8,
    "tgt": 11,
    "car": 0
   },
   {
    "w": 3,
    "team": "CHI",
    "role": 13.06,
    "prod": 15.2,
    "tgt": 7,
    "car": 0
   },
   {
    "w": 4,
    "team": "CHI",
    "role": 17.0,
    "prod": 16.9,
    "tgt": 8,
    "car": 0
   },
   {
    "w": 6,
    "team": "CHI",
    "role": 9.06,
    "prod": 5.2,
    "tgt": 5,
    "car": 0
   },
   {
    "w": 7,
    "team": "CHI",
    "role": 8.78,
    "prod": 5.1,
    "tgt": 6,
    "car": 0
   },
   {
    "w": 8,
    "team": "CHI",
    "role": 17.88,
    "prod": 18.4,
    "tgt": 10,
    "car": 0
   },
   {
    "w": 9,
    "team": "CHI",
    "role": 8.11,
    "prod": 0.0,
    "tgt": 3,
    "car": 0
   },
   {
    "w": 10,
    "team": "CHI",
    "role": 20.13,
    "prod": 20.6,
    "tgt": 10,
    "car": 0
   },
   {
    "w": 11,
    "team": "CHI",
    "role": 14.23,
    "prod": 6.1,
    "tgt": 6,
    "car": 0
   },
   {
    "w": 12,
    "team": "CHI",
    "role": 15.68,
    "prod": 8.3,
    "tgt": 9,
    "car": 0
   },
   {
    "w": 13,
    "team": "CHI",
    "role": 9.83,
    "prod": 2.8,
    "tgt": 6,
    "car": 0
   }
  ],
  "jobRank": 12,
  "priceRank": 20,
  "poolSize": 93,
  "modelRank": 33,
  "modelPool": 93
 }
];
export const NO_TAPE = [
 {
  "sleeperId": "13276",
  "name": "Omar Cooper",
  "pos": "WR",
  "age": 22,
  "exp": 0,
  "mktValue": 1938.0
 },
 {
  "sleeperId": "13311",
  "name": "Chris Bell",
  "pos": "WR",
  "age": 22,
  "exp": 0,
  "mktValue": 1405.0
 },
 {
  "sleeperId": "13414",
  "name": "Kaelon Black",
  "pos": "RB",
  "age": 24,
  "exp": 0,
  "mktValue": 1055.0
 },
 {
  "sleeperId": "9502",
  "name": "Tank Dell",
  "pos": "WR",
  "age": 26,
  "exp": 3,
  "mktValue": 1295.0
 }
];
