import { chromium } from '/Users/davidleess/dynasty-genius-product/frontend/node_modules/playwright/index.mjs';
const P = '/Users/davidleess/frontend-studio/proposals/001-morning-tape/prototype.html';
const A = '/Users/davidleess/frontend-studio/proposals/assets/001-proto';
const browser = await chromium.launch();
let page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', e => console.log('PAGE ERR:', e.message.slice(0, 200)));
await page.goto('file://' + P, { waitUntil: 'networkidle' });
await page.waitForTimeout(900);
await page.screenshot({ path: A + '/p4-final-top.png' });
await page.screenshot({ path: A + '/p4-final-full.png', fullPage: true });
await page.getByRole('button', { name: 'receipts' }).click();
await page.waitForTimeout(300);
await page.screenshot({ path: A + '/p5-final-receipts.png' });
await page.close();
page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.goto('file://' + P, { waitUntil: 'networkidle' });
await page.waitForTimeout(700);
await page.screenshot({ path: A + '/p6-mobile.png' });
console.log('done');
await browser.close();
